#!/usr/bin/env ruby
# NOCOMMIT_IS_OK_HERE: This script creates pre-commit git hook that detects the text
# NOCOMMIT_IS_OK_HERE: "NOCOMMIT" in the text. If found, git will abort the commit with a
# NOCOMMIT_IS_OK_HERE: big warning message telling you that you have marked a file as being
# NOCOMMIT_IS_OK_HERE: not committable.
# NOCOMMIT_IS_OK_HERE:
# NOCOMMIT_IS_OK_HERE: Example:
# NOCOMMIT_IS_OK_HERE:
# NOCOMMIT_IS_OK_HERE: # NOCOMMIT: Hacks
# NOCOMMIT_IS_OK_HERE: x / 0 # NOCOMMIT: This is probably a bad idea
# NOCOMMIT_IS_OK_HERE:
# NOCOMMIT_IS_OK_HERE: You can override this by ALSO adding NOCOMMIT_IS_OK_HERE to THE SAME line.
# NOCOMMIT_IS_OK_HERE:
# NOCOMMIT_IS_OK_HERE: Example:
# NOCOMMIT_IS_OK_HERE:
# NOCOMMIT_IS_OK_HERE: def mark_line_as_nocommit(message)
# NOCOMMIT_IS_OK_HERE:     puts '# NOCOMMIT: #{message}' # NOCOMMIT_IS_OK_HERE
# NOCOMMIT_IS_OK_HERE: end
# NOCOMMIT_IS_OK_HERE:
# NOCOMMIT_IS_OK_HERE: Installation:
# NOCOMMIT_IS_OK_HERE:     With this script in your path, cd to the root of your project
# NOCOMMIT_IS_OK_HERE: and run "add-nocommit". This will create the magical pre-commit
# NOCOMMIT_IS_OK_HERE: file.
# NOCOMMIT_IS_OK_HERE:
# NOCOMMIT_IS_OK_HERE: Usage:
# NOCOMMIT_IS_OK_HERE:     Just add a comment like:
# NOCOMMIT_IS_OK_HERE:
# NOCOMMIT_IS_OK_HERE: NOCOMMIT: this file has sensitive data / is bogus / etc!
# NOCOMMIT_IS_OK_HERE:
# NOCOMMIT_IS_OK_HERE: and if you forget and accidentally git add the file, the commit will
# NOCOMMIT_IS_OK_HERE: fail, showing you the file and line containing the NOCOMMIT message.

def barf!(msg=nil)
  puts "*** add-nocommit: %s " % msg if msg
  exit -1
end

precommit_folder = "./.git/hooks"
precommit_file = "%s/pre-commit" % precommit_folder

barf! "Pardon me, but I'm lost. Is this a git repo? I don't see .git/hooks/ here!" unless File.directory? precommit_folder
if !ARGV.include?("-f") && !ARGV.include?("--force")
  barf! "Cowardly refusing to overwrite existing pre-commit hook!" if File.exist? precommit_file
end

File.open(precommit_file, 'w') do |file|
  file.puts DATA.read
end
system("chmod a+x #{precommit_file}")

__END__
#!/usr/bin/env ruby

# NOCOMMIT_IS_OK_HERE: git-hook to check for NOCOMMIT messages in code that has
# NOCOMMIT_IS_OK_HERE: been staged and abort the commit if found.
# NOCOMMIT_IS_OK_HERE:
# NOCOMMIT_IS_OK_HERE: To use: copy this file into your .git/hooks folder as pre-commit and make sure
# NOCOMMIT_IS_OK_HERE: it is executable (chmod +x pre-commit). Now in your code, type // NOCOMMIT or
# NOCOMMIT_IS_OK_HERE: # NOCOMMIT in a line and save it -- usually with an explanatory message like
# NOCOMMIT_IS_OK_HERE: "# NOCOMMIT -- temp hack for bug #123".  Git will still let you stage the file
# NOCOMMIT_IS_OK_HERE: with git add, but it will stop you from committing the file until you remove
# NOCOMMIT_IS_OK_HERE: the NOCOMMIT comment.
file = ""
delta = ""
line_num = 0
`git diff-index -p -M --cached HEAD`.each_line do |line|
  file = line.sub(/^....../, '') if line =~ /^(---|\+\+\+) (a|b)\//
  if line =~ /^@@ [\-\+\,\d\s]+ @@$/
    delta = line.rstrip
    if line =~ /\d \+(\d+),\d/
      line_num = $1.to_i - 1
    else
      line_num = 0
    end
  else
    line_num += 1 if line !~ /^- /
  end

  if !line.start_with?("-") && line =~ %r{NOCOMMIT} && line !~ /NOCOMMIT_IS_OK_HERE/
    puts <<BANNER
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!                                                                           !!!
!!!  ##    ##   ####     ####     ####   ##    ## ##    ##   ####   ########  !!!
!!!  ###   ## ##    ## ##    ## ##    ## ###  ### ###  ###    ##       ##     !!!
!!!  ####  ## ##    ## ##       ##    ## ## ## ## ## ## ##    ##       ##     !!!
!!!  ## ## ## ##    ## ##       ##    ## ##    ## ##    ##    ##       ##     !!!
!!!  ##  #### ##    ## ##       ##    ## ##    ## ##    ##    ##       ##     !!!
!!!  ##   ### ##    ## ##    ## ##    ## ##    ## ##    ##    ##       ##     !!!
!!!  ##    ##   ####     ####     ####   ##    ## ##    ##   ####      ##     !!!
!!!                                                                           !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!                                                                           !!!
!!!                                                                           !!!
!!!           COMMIT ABORTED: You are staging a file with NOCOMMIT!           !!!
!!!                                                                           !!!
!!!                                                                           !!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

BANNER
    puts "In file: #{file}"
    puts "In delta #{delta} near line #{line_num}:"
    puts line
    exit 1
  end
end

# Check to see if we're on master
branch=`git current-branch`.strip
main_branch=`git main-branch`.strip

if branch == "hermes-master" || branch == main_branch
  puts '\033[1;37;41m                             \033[0m'
  puts '\033[1;37;41m            STOP!!!          \033[0m'
  puts '\033[1;37;41m                             \033[0m'
  puts '\033[1;37;41m  YOU ARE ON A MAIN BRANCH!  \033[0m'
  puts '\033[1;37;41m STOP TRYING TO COMMIT THIS! \033[0m'
  puts '\033[1;37;41m                             \033[0m'
  exit 1
end

exit 0
