#!/bin/bash
#
#   This file echoes a bunch of color codes to the
#   terminal to demonstrate what's available.  Each
#   line is the color code of one forground color,
#   out of 17 (default + 16 escapes), followed by a
#   test use of that color on all nine background
#   colors (default + 8 escapes).

# Got tired of waiting 4-7 seconds for this thing to render, let's cache it. Bam. 15ms.
cat ~/bin/ansichart.txt
exit 0

# Here is the generator script. Comment out the above and run this instead:


#
#   Author: Giles Orr
#   URL: http://gilesorr.com/bashprompt/howto/c333.html#AEN335
#   License: GNU Free Documentation License, Version 1.1 or any later version published by the Free Software Foundation;
#            http://gilesorr.com/bashprompt/howto/a1004.html

FORMAT=" %8s "
echo -ne "\nv FG \ BG >   "
for bg in 40m 100m  41m 101m  42m 102m  43m 103m 44m 104m  45m 105m  46m 106m 47m 107m; do
    printf "$FORMAT" $bg
done
echo

line=0
for FGs in '2;30m' '  30m' '  90m' '1;30m' \
                   '2;31m' '  31m' '  91m' '1;31m' \
                   '2;32m' '  32m' '  92m' '1;32m' \
                   '2;33m' '  33m' '  93m' '1;33m' \
                   '2;34m' '  34m' '  94m' '1;34m' \
                   '2;35m' '  35m' '  95m' '1;35m' \
                   '2;36m' '  36m' '  96m' '1;36m' \
                   '2;37m' '  37m' '  97m' '1;37m' ; do
  FG=${FGs// /}
  case $(expr $line % 4) in
      0)
          echo -n "dim    "
          ;;
      1)
          echo -n "normal "
          ;;
      2)
          echo -n "light  "
          ;;
      3)
          echo -n "bold   "
          ;;
  esac
  line=$(expr $line + 1)
  echo -en " $FGs \033[$FG"
  FGCLEAN=`echo $FG | sed -e 's/m//'`

  for BG in 40m 100m 41m 101m 42m 102m 43m 103m 44m 104m 45m 105m 46m 106m 47m 107m; do
      BGCLEAN=`echo $BG | sed -e 's/m//'`
      echo -en "\033[$FG\033[$BG";
      printf "$FORMAT" "$FGCLEAN;${BGCLEAN}"
      echo -en "\033[0m";
  done
  echo;
done

echo "0 to 7 are the basic colors; add an offset to use it as desired:"
echo "30-37: foreground, 90-97 foreground bright. 40-47 background, 100-107 background bright"
echo "Extra attributes: 1 bold, 2 dim, 4 underline, 7 reverse, 8 hidden"
echo "Clear attributes: 20 color, 21 bold, 22 dim, etc. 0 clears everything, including color"
echo
echo "Example: print '(color)' in bold underlined green on red background:"
echo "echo -e \\033[41;1;4;32m(color)\\033[0m"
echo -e "\033[1;4;32;41m(color)\033[0m"
echo
echo "NOTE: -e is required to turn on extended colors. It is undocumented on OSX, and does"
echo "not work under /bin/sh on Catalina. Use /bin/bash"
echo
echo "In the wild, you may also see \x1b; it is the hex equivalent of octal \033."
