#!/bin/bash
# quiet mode: exits silently and returns bash status !!(we are logged in)
# normal mode: prints "You are logged in" or not (and return bash status)
#
if [ "$1" == "-q" ]; then
    aws sts get-caller-identity --profile NonProdDeveloperAccess-574644123169 --query "Account" > /dev/null 2>&1
else
    aws sts get-caller-identity --profile NonProdDeveloperAccess-574644123169 --query "Account" > /dev/null 2>&1 && echo "You are logged in to AWS." || (echo "You are NOT logged in to AWS" && /usr/bin/false)
fi
