#!/bin/bash

# backlog - Show the review backlog, beacuse I've renamed that stupid file twice
# and keep forgetting where snow-make-links puts it.

if [ "$IS_DOCKER_LOCAL" == "1" ]; then
    # docker
    FILENAME="/root/data_services/review-backlog.log"
else
    # osx
    FILENAME="/Users/david.brady/acima/devel/data_services/review-backlog.log"
fi

if [ "$1" == "clear" ]; then
    echo -e "\033[36mecho '' > $FILENAME\033[0m"
    echo '' > $FILENAME
else
    echo -e "\033[36mcat $FILENAME \033[0m"
    cat $FILENAME
fi
