#!/usr/bin/env ruby
# bails - bin/bundle exec rails, ensuring that aws login is current
require "colorize"
require "optimist"
require_relative "dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  def time?
    opts[:time]
  end

  def run
    @opts = Optimist.options do
      opt :debug, "Print extra debug info", default: false
      opt :pretend, "Print commands but do not run them", default: false
      opt :verbose, "Run with verbose output (overrides --quiet)", default: false
      opt :quiet, "Run with minimal output", default: false
      opt :time, "Time command", default: false

      opt :tasks, "List tasks", short: :T, default: false
    end
    opts[:quiet] = !opts[:verbose] if opts[:verbose_given]
    puts opts.inspect if opts[:debug]

    ensure_aws_sso_login
    command = "bundle exec rails #{arglist}"
    command = "time #{command}" if time?
    run_command command
  end

  def passthrough_args
    # For now we have to whitelist any args we want to pass through to rails
    # TODO: Is there a way take make Optimist leave args it doesn't recognize in ARGV?
    {
      tasks: "-T"
    }.map {|option, arg| arg if opts[option] }.compact
  end

  def arglist
    (passthrough_args + ARGV.map {|arg| arg.match(/\s+/) ? arg.inspect : arg }).join(' ')
  end

  def ensure_aws_sso_login
    run_command("aws sso login") unless run_command("aws-check-sso-login -q")
  end

end


if __FILE__ == $0
  Application.new.run
end
