#!/usr/bin/env ruby
# basic-auth - generate the basic auth header from api key and token

# for use wherever fine curl -H "Authorization: Basic JABBERJABBERJABBER" are sold

api_key, api_secret = *ARGV

require 'base64'

puts "Basic Authorization Token for api_key '#{api_key}' and secret '#{api_secret}':"
puts "Use this with curl -H \"Authorization: Basic BLAH\""
puts Base64.encode64(api_key + ":" + api_secret)
