#!/usr/bin/env ruby
# bearer-auth - generate the bearer auth header from username and access token

# Remember that BASIC authorization will Base64 encode your junk, but Bearer
# authorization is always in cleartext separated by a +. So:
# for use wherever curl -H "Authorization: Bearer username+password" works

api_key, token = *ARGV
api_key ||= ""
token ||= ""

puts "REMEMBER: Bearer authorization is not base64 encoded, but Basic auth is."
puts "Bearer Authorization Token for api_key '#{api_key}' and token '#{token}':"
authtext = api_key + "+" + token

puts "Use this with curl -H \"Authorization: Bearer #{authtext}\""
