#!/bin/bash
# hueloop - turn on colorloop effect
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |
#
# Bedroom Lamps - 7 & 8

for lamp in 7 8; do
    curl -X PUT "http://$HUE_IP/api/$HUE/lights/$lamp/state" -d  '{"on": true, "bri": 0, "hue": 46920, "sat": 254, "transitiontime":0}' 2>/dev/null > /dev/null
done
for lamp in 7 8; do
    curl -X PUT "http://$HUE_IP/api/$HUE/lights/$lamp/state" -d  '{"on": true, "bri": 254, "sat": 254, "effect": "colorloop"}' 2>/dev/null > /dev/null
done
