#!/usr/bin/env ruby
# bstubes - examine Beanstalk Queue Tube status

require 'rubygems'
require 'ruport'
require 'trollop'
require 'beanstalk-client'

opts = Trollop.options do
  opt :port, "port", :type => :integer, :default => 11300
  opt :host, "host", :default => "localhost"
end

table = Ruport::Data::Table(%w[tube delayed ready reserved buried])

hostport = "#{opts[:host]}:#{opts[:port]}"

bs = Beanstalk::Pool.new([hostport])

bs.list_tubes[hostport].each do |tube|
  h = {"tube" => tube}
  %w[delayed ready reserved buried].each do |state|
    h[state] = bs.stats_tube(tube)["current-jobs-#{state}"]
  end
  table << h
end

h = { "tube" => "TOTAL" }
%w[delayed ready reserved buried].each do |col|
  h[col] = table.sum(col)
end
table << h

puts table


