#!/bin/bash
# cdp-save <name> - save ~/.current-project to ~/.current-project.name
# I am useful when set-current-project starts repeatedly iterating over multple targets
PROJ_FILE=~/.current-project
USAGE="cdp-save <name> - save ~/.current-project to ~/.current-project.name"

function barf {
    if [ "$1" != "" ]; then
        echo "BARF: $1"
    fi
    echo $USAGE
    exit 1
}

# test number of args
if [ $# != 1 ]; then
    barf "Must supply exactly 1 argument"
fi

# test for help
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo $USAGE
    exit 1
fi

# barf if ~/.current-project doesn't exist
if [ ! -e $PROJ_FILE ]; then
    barf "$PROJ_FILE does not currently exist. Load it with cdp-load or create it with set-current-project"
fi

# barf if $! contains a space
if grep -Eq "\s" <<<$1 ; then
    barf "No spaces allowed in project name, sorry"
fi

# ======================================================================
# MAIN SCRIPT (FINALLY LOL)
echo cp $PROJ_FILE{,.$1}
cp $PROJ_FILE{,.$1}

echo "Saved current project file to $1:"
head -n 1 "$PROJ_FILE.$1"
