#!/usr/bin/env ruby
# ci-deadman - turn off ci lights every so often
require "colorize"
require_relative "dbrady_cli"
require "optimist"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  def cioff
    run_command "cioff"
  end

  def ciwhite
    run_command "ciwhite"
  end

  def is_during_work_hours?(time)
    (8..17).include?(time.hour) && (1..5).include?(time.wday)
  end

  def run
    @opts = Optimist.options do
      opt :debug, "Print extra debug info", default: false
      opt :n, "Number of seconds between turnoff attempts", type: :int
      # opt :hourly
      opt :time, "Display time to next shutoff", default:  false
    end
    puts opts.inspect if opts[:debug]

    while true
      now = Time.now
      # if is_during_work_hours?(now) then ciwhite else cioff end
      system "clear && rubanner --font=miniwi --bg light_black 'ci-deadman' '#{now.strftime('%F %T')}'"
      cioff
      seconds_to_sleep = 3600 - (now.min * 60 + now.sec)

      puts now.strftime("%T") unless quiet?
      puts "Sleeping for #{seconds_to_sleep} seconds..." unless quiet?
      sleep seconds_to_sleep
    end
  end
end


if __FILE__ == $0
  Application.new.run
end
