#!/bin/bash
touch ~/.ciblink

# blink 100 times (200 sec) or until ~/.ciblink vanishes
for i in 1 2 3 4 5 6 7 8 9 10; do
         if [ -e ~/.ciblink ]; then
             for j in 1 2 3 4 5 6 7 8 9 10; do
                      cipass
                      sleep 1
                      cioff
                      sleep 1
             done
         fi
done
