#!/bin/bash
touch ~/.ciblink

# blink 100 times (200 sec) or until ~/.ciblink vanishes
for i in $(seq 3); do
    if [ -e ~/.ciblink ]; then
        cipass
        sleep 1
        cioff
        sleep 1
    fi
done
