#!/bin/sh
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |

rubanner --font=electronic "THINKY" light_cyan on_white
# From the concentrate recipe
curl -X PUT "http://192.168.0.66/api/$HUE/lights/9/state" -d  '{"on": true, "bri": 254, "hue": 33862, "sat": 50, "transitiontime":0}' 2>/dev/null > /dev/null
