#!/bin/sh
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |
#rubanner --font=electronic "FAIL" bold on_red
rubanner --font=electronic "FAIL" white on_red
#curl -X PUT "http://$HUE_IP/api/$HUE/lights/9/state" -d '{"on":true, "bri":254,"sat":254,"hue":0, "transitiontime":0}' 2>/dev/null > /dev/null
# I'm in Ohio, baby
curl -X PUT "http://$HUE_IP/api/$HUE/lights/3/state" -d '{"on":true, "bri":64,"sat":254,"hue":0, "transitiontime":0}' 2>/dev/null > /dev/null
