#!/bin/sh
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |
#
# Office Lamp Arrangement 2018
# 4 - Office Spotlight
# 9 - Office Lightstrip
# 10 - Office Light Fixture (North Bulb)
# 11 - Office Light Fixture (South Bulb)

curl -X PUT "http://$HUE_IP/api/$HUE/lights/5/state" -d '{"on":true, "sat":254, "bri":254, "transitiontime":0}' 2>/dev/null > /dev/null
