#!/bin/sh
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |

# rubanner --font=electronic "PASS" bold on_green
rubanner --font=electronic "PASS" white on_green
# GEEZ MAN FIGURE OUT groups
# 4 - Upstairs office spot
# 9 - Lightstrip in upstairs office
if [ -e ~/onsite.touch ]; then
    echo "You're onsite! Skipping HUE lights."
else
    for light in 4 9; do
        curl -X PUT "http://$HUE_IP/api/$HUE/lights/$light/state" -d '{"on":true, "bri":254,"sat":254,"hue":25000, "transitiontime":0}' 2>/dev/null > /dev/null
    done
    # the spotlight is wayyyy too strong, let's back it off
    sleep 1
    curl -X PUT "http://$HUE_IP/api/$HUE/lights/4/state" -d  '{"on": true, "bri": 254, "hue": 33862, "sat": 50, "transitiontime":0}' 2>/dev/null > /dev/null
fi
