#!/bin/sh
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |
#
# Office Lamp Arrangement 2018
# 4 - Office Spotlight
# 5 - Main Floor Office Lighstrip
# 9 - Upstairs Office Lightstrip
# 10 - Office Light Fixture (North Bulb)
# 11 - Office Light Fixture (South Bulb)

rubanner --font=electronic --bold --fg=white --bg=green "PASS"
if [ -e ~/onsite.touch ]; then
    # echo "You're onsite! Skipping HUE lights."
    exit 0
else
    for light in 5; do
        curl -X PUT "http://$HUE_IP/api/$HUE/lights/$light/state" -d '{"on":true, "bri":254,"sat":254,"hue":25000, "transitiontime":0}' 2>/dev/null > /dev/null
    done
    # the spotlight is wayyyy too strong, let's back it off
    sleep 1
    curl -X PUT "http://$HUE_IP/api/$HUE/lights/4/state" -d  '{"on": true, "bri": 254, "hue": 33862, "sat": 50, "transitiontime":0}' 2>/dev/null > /dev/null
fi

# force an exit 0. Callers use this script like do_something && cipass ||
# cifail; so if do_something succeeds but an error occurs during cipass, it will
# crashcade down into cifail, giving a perplexing double-banner of PASS *and*
# FAIL. #SchroedingersTestSuite
exit 0
