#!/bin/sh
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |

if [ -e ~/onsite.touch ]; then
    # echo "You're onsite! Skipping HUE lights."
    exit 0
else
    for light in 5; do
        curl -X PUT "http://$HUE_IP/api/$HUE/lights/$light/state" -d '{"on":true, "bri":254,"sat":0,"hue":0, "transitiontime":0}' 2>/dev/null > /dev/null
    done
fi
