#!/bin/bash

# This has been on for long enough -- I'm overriding it 100% of the time.
# Rather than condition me for alert fatigue, let's just accept my nescience as
# documented.
# echo -e '\033[2;30;103m        DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER        \033[0m'
# echo -e '\033[2;30;103m         DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGE        \033[0m'
# echo -e '\033[2;30;103m        R DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANG        \033[0m'
# echo -e '\033[2;30;103m        ER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DAN        \033[0m'
# echo -e '\033[2;30;103m        GER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DA        \033[0m'
# echo -e '\033[2;30;103m        NGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER D        \033[0m'
# echo -e '\033[2;30;103m        ANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER         \033[0m'
# echo -e '\033[2;30;103m        DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER DANGER        \033[0m'
# echo
# echo "This will run claude --dangerously-skip-permissions $@"
# echo
# echo 'Are you an idiot [Y/y]'
# read
echo -e '\033[1;33mexec claude --dangerously-skip-permissions $@\033[0m'
exec claude --dangerously-skip-permissions $@
