#!/bin/sh
# cls - clear screen by echoing 24 blank lines
#
# tbh it's mostly useful to create a big whitespace in my scrollback, but
# "inject-a-bunch-of-whitespace" is harder to type

# Update: adding this to my bin repo because although pig-stupid it's proven
# quite useful in breaking up the scrollback buffer
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
