#!/usr/bin/env ruby
# csv-to-table - Print a csv file as a text table
# Usage:
#     csv-to-table filename.csv
#     cat filename.csv | csv-to-table
#     curl https://example.org/somefile.csv | csv-to-table
#
# TODO:
# Add -n option: number of lines to read
# Add -s, -t option: number of lines offset from start or backwards from tail
# E.g.
# read the second batch of 10 lines from the end: -n 10 -t 20
# read lines 1000-1100: -s 1000 -n 100
require "csv"

begin
  require "text-table"
rescue LoadError
  puts "Cannot load text-table, please do:"
  puts "gem install text-table"
  puts "And try again."
  exit -1
end

csv = ARGF.readlines.join
puts CSV.parse(csv, headers: true).to_a.to_table(first_row_is_head: true)
