#!/usr/bin/env ruby
# csv_to_table - Print a csv file as a text table
# Usage:
#     csv_to_table filename.csv
#     cat filename.csv | csv_to_table
#     curl https://example.org/somefile.csv | csv_to_table

require "csv"

begin
  require "text-table"
rescue LoadError
  puts "Cannot load text-table, please do:"
  puts "gem install text-table"
  puts "And try again."
  exit -1
end

csv = ARGF.readlines.join
puts CSV.parse(csv, headers: true).to_a.to_table(first_row_is_head: true)
