#!/usr/bin/env ruby
unless defined? Rails
  puts "Run me with rails runner!"
  exit 1
end

if ARGV.count > 0
  file = ARGV.pop
else
  file = "./config/database.yml"
end

puts Erubis::Eruby.new(File.read(file)).result binding
