#!/usr/bin/env ruby
unless defined? Rails
  cmd = "bundle exec rails runner #{__FILE__}"
  puts cmd
  system cmd
  exit $?.to_i
end

if ARGV.count > 0
  file = ARGV.pop
else
  file = "./config/database.yml"
end

puts Erubis::Eruby.new(File.read(file)).result binding
