#!/usr/bin/env ruby

# denviro - Dump ENVIROnment - cat a file in Rails environment with
# interpolations

# Usage: denviro [<file>] - if file is omitted, assumes ./config/database.yml

# TL;dr:
# rails r 'puts ERB.new(File.read("./config/database.yml")).result(binding)'

# Why: Because sometimes I open a settings.yml or config/database.yml and it's
# so full of <%= ... %> garbage that I have no idea what's going on. One gig in
# particular placed even the developer-facing side of this information behind
# the same layers of armor and secrets managment as the production code, making
# such a problem that writing a custom solution became necessary to prevent
# developer revolt. (It was an in-house gem called Enviro, hence the name of
# this script).

# Part I - If you launched this script without rails runner, relaunch itself
# under rails runner
unless defined? Rails
  cmd = "bundle exec rails runner #{__FILE__}"
  puts cmd
  system cmd
  exit $?.to_i
end

# Part II - Accept an arg for  filename to parse. Defaults to config/database.yml
if ARGV.count > 0
  file = ARGV.pop
else
  file = "./config/database.yml"
end

# Part III - Load it, bind it, parse it, puts it
# puts Erubis::Eruby.new(File.read(file)).result binding
puts ERB.new(File.read(file)).result(binding)
