#!/bin/bash
# For use when Chrome goes permanently out to lunch.
# I'm not sad. I AM ANGRY. DIE, CHROME, DIE.

# MAKE UP YOUR FUCKING MIND, GOOGLE
#GOOGLE_PROCESS_NAME_THIS_WEEK=/opt/google/chrome
#GOOGLE_PROCESS_NAME_THIS_WEEK=chromium-browser
GOOGLE_PROCESS_NAME_THIS_WEEK="Google Chrome"
ps auwx | grep "$GOOGLE_PROCESS_NAME_THIS_WEEK" | awk '{ print $2 }' | while read pid; do kill -9 $pid 2>&1 > /dev/null; done
