#!/bin/bash
# because compliance keeps turning on services that lock up my cpu when ntpd can't find a server it likes
echo "Killing ntpd with fire..."
echo "ps auwx | grep [n]tpd | grep -v dientpddie"
ps auwx | grep [n]tpd | grep -v dientpddie
ps auwx | grep [n]tpd | grep -v dientpddie | awk '{print $2}' | while read pid; do
    echo sudo kill -9 $pid
    sudo kill -9 $pid
done
