#!/bin/bash

echo "Checking for running spring processes..."
ps auxw | grep [s]pring | grep -v diespringdie
echo

echo "Asking spring politely to go quietly into that good night..."
echo -e "\033[36mps auwx | grep [s]pring | grep -v diespringdie | awk '{ print \$2 }' | while read pid; do echo \"pid: \$pid\"; kill \$pid; done\033[0m"
ps auwx | grep [s]pring | grep -v diespringdie | awk '{ print $2 }' | while read pid; do echo "pid: $pid"; kill $pid; done
echo

echo "Giving spring a moment to shut itself down..."
echo -e "\033[36msleep 5\033[0m"
sleep 5

echo "Telling the OS to go after spring with a machete..."
echo -e "\033[36mps auwx | grep [s]pring | grep -v diespringdie | awk '{ print \$2 }' | while read pid; do echo \"pid: \$pid\"; kill -9 \$pid; done\033[0m"
ps auwx | grep [s]pring | grep -v diespringdie | awk '{ print $2 }' | while read pid; do echo "pid: $pid"; kill -9 $pid; done
