#!/bin/sh
SCRIPT=dot
OSX_PREVIEW="true"

# LOLBASH: You can use -p to open in preview automatically OR you can say -f
# neato but I'm too dumb right now to figure out how to allow "-p -f neato"
#
# But I'm so tired of doing dot2png filename.dot && open filename.png that I'm
# calling this good enough for now. Debug me later. Ship it now: EITHER argument
# will work, just not both at once.
while getopts "pf:" opt; do
    case $opt in
        f)
            case $OPTARG in
                dot|neato|twopi|circo|fdp|sfdp)
                    SCRIPT=$OPTARG
                    ;;
                *)
                    echo "Invalid formatter '$OPTARG'. Must be one of: dot, neato, twopi, circo, fdp, sfdp"
                    exit 1
                    ;;
            esac
            shift
            shift
            ;;
        p)
            if [ `uname -s` == "Darwin" ]; then
                OSX_PREVIEW="true"
            else
                echo "Invalid option: -p turns on OSX preview; expected operating system to be 'Darwin' but uname -s detected '`uname -s`' instead"
                exit 1
            fi
            shift
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

echo "Using formatter '$SCRIPT'"
echo $SCRIPT -T png -o $(basename $1 .dot).png $1
$SCRIPT -T png -o $(basename $1 .dot).png $1

if [ "$(uname -s)" = "Darwin" ]; then
    if [ $OSX_PREVIEW == "true" ]; then
        open $(basename $1 .dot).png
    fi
fi
