#!/usr/bin/env ruby
# ds-announce-ssh-tunnel - jam out a big green page so I know my
# ssh tunnel has (re)connected
require 'io/console'
y,x = $stdout.winsize

message = if x > 60
            "SSH TUNNEL"
          else
            "SSH"
          end
command = "rupage --font=ansi-shadow --bold --fg=white --bg=green '#{message}'"
system command
