#!/bin/bash
FILE1="$1"
FILE2="$2"

if [ "$FILE1" == "" ]; then
    FILE1="dscmp.redshift.csv"
fi

if [ "$FILE2" == "" ]; then
    FILE2="dscmp.snowflake.csv"
fi

cat "$FILE1" | ruby -ne 'puts "#{($.==1) ? "warehouse" : "redshift" },#{$_}"'
behead "$FILE2" | ruby -ne 'puts "snowflake,#{$_}"'
