#!/bin/bash
# ds-docker-setup-3-apt-packages - Customize My Docker Setup

apt-get install -y \
        dnsutils \
        emacs \
        figlet \
        iputils-ping \
        jq \
        less \
        man \
        mtr \
        net-tools \
        python3-autopep8 \
        silversearcher-ag \
        tree
