#!/bin/bash
# ds-docker-setup-2-clone-repos - Customize My Docker Setup
(
    echo "Cloning Repos" &&
        cd &&
        [ ! -d ~/bin ] && git clone git@github.com:dbrady/bin.git &&
        [ ! -d ~/dotfiles ] && git clone git@github.com:dbrady/dotfiles.git &&
        [ ! -d ~/.emacs.d ] && git clone git@github.com:dbrady/prelude.git .emacs.d &&
        mkdir -f ~/devel && cd &&
        [ ! -d ~/devel/scrapbin ] && (cd ~/devel && git clone git@github.com:dbrady/scrapbin.git) &&
        [ ! -d ~/devel/scrapbin ] && (cd ~/devel && git clone git@github.com:dbrady/refdox.git) &&

        echo "All done!"
)
