#!/bin/bash

if [ "$IS_DOCKER_LOCAL" == "1" ]; then
    watch -d -n 60 'git log-branch -p $HOME/bin; git log-branch -p $HOME/data_services; git log-branch -p $HOME/data_services_package/; git log-branch -p $HOME/data_services/etl/warehouse/finance/; git log-branch -p $HOME/data_services/etl/warehouse/sql'
else
    watch -d -n 60 'git log-branch -p $HOME/acima/devel/bin; git log-branch -p $HOME/acima/devel/data_services; git log-branch -p $HOME/acima/devel/data_services_package/; git log-branch -p $HOME/acima/devel/data_services/etl/warehouse/finance/; git log-branch -p $HOME/acima/devel/data_services/etl/warehouse/sql'
fi
