#!/bin/bash
# dsbuild - build docker image
#
# See Also:
# dsrun - create container from image (also starts it and joins it)
# dsstart - boots a container (and joins it)
# dsexec - joins a running container
if [ `uname -s` != 'Darwin' ]; then
    echo "Must be run from OSX, outside the docker container."
    exit
fi

echo docker build -t data_services:latest -f ~/develop/data_services/config/docker/Dockerfile ~/develop/.
docker build -t data_services:latest -f ~/develop/data_services/config/docker/Dockerfile ~/develop/.
