#!/usr/bin/env ruby
# dscmp <query> - Compare query results in both warehouses
#

# TODO: I want to feed in pig-stupid-but-mother-huge queries from BI. I have to
# put them in a file. I thought about jamming in a --file=<path/to/file.sql>
# option but this script does too much query manipulation, and my instinct is to
# either try to support it all or to spend the time documenting to Future Me
# that it does not do query manipulation on the file.
#
# For now, I'm just doing this:
#
# for warehouse in redshift snowflake; do echo querying $warehouse...; dsquery --warehouse=$warehouse --file=ds-3313-one-agent.sql | cleanup-whitespace > dscmp.${warehouse}.csv; done

require "colorize"
require "optimist"

opts = Optimist.options do
  banner <<HALP
dscmp - Compare query between redshift and snowflake

dscmp <options> --query="SELECT foo FROM bar WHERE blah"
dscmp <options> --query="SELECT blah FROM whatever WHERE id={ids}" --redshift=42 --snowflake=13
dscmp <options> --query="SELECT blah FROM whatever WHERE id IN ({ids})" --redshift="42, 43" --snowflake="13, 14

Options:
HALP
  opt :csv, "Emit output in csv format instead of datatables", default: false
  opt :finance, "Use finance warehouses", default: false
  opt :log, "Write query outputs to dscmp.{warehouse}.log", default: false
  opt :pretty, "Format table all pretty-like", default: false
  opt :query, "Query to use, use {ids} to fill from --redshift=value, --snowflake=value", type: :string, required: false

  opt :redshift, "Values to use in redshift as {ids}", type: :string
  opt :snowflake, "Values to use in snowflake as {ids}", type: :string
  opt :redshift2, "Query fragment (ids, rs-specific sql) to use in redshift as {query}", type: :string
  opt :snowflake2, "Query fragment (ids, snow-specific sql) to use in snowflake as {query}", type: :string
end

opts[:csv] = true if opts[:pretty]

warehouses = if opts[:finance]
               %w(redshift_finance snowflake_finance)
             else
               %w(redshift snowflake)
             end

warehouses.each do |warehouse|
  # override query if given
  query = opts[:query] || ARGV.last
  if opts[:redshift_given] && warehouse =~ /redshift/
    query = query.gsub(/{ids}/, opts[:redshift]).gsub(/{query}/, opts[:redshift2])
  elsif opts[:snowflake_given] && warehouse =~ /snowflake/
    query = query.gsub(/{ids}/, opts[:snowflake]).gsub(/{query}/, opts[:snowflake2])
  end

  color = case warehouse
          when /redshift/ then :light_red
          when /snowflake/ then :cyan
          else :white
          end

  command = %Q(dsquery #{opts[:csv] ? '--csv ' : ''}--warehouse #{warehouse} --query "#{query}" | cleanup-whitespace #{opts[:pretty] ? "| snow-table" : ""})
  command += " | tee dscmp.#{warehouse}.csv" if opts[:log]
  puts (command  + " # #{warehouse}").send(color)
  system command
end
