#!/bin/bash
# dsetl - selecta to pick a job, then run it with etl_nightly
# See Also: (ds* scripts for inside the docker container)
# dsinstall
# dsetl
# dsetl_nightly

if [ "$IS_DOCKER_LOCAL" != "1" ]; then
    echo "Must be run from inside the docker container."
    exit
fi

pushd ~/data_services/etl/warehouse

JOB=`find . -name '*.py' | grep "$1" | selecta | sed -e 's|^[/.]*||'`
echo '#' python etl_nightly.py --job "$JOB"
python etl_nightly.py --job "$JOB"
popd
