#!/bin/bash
# dsetl - selecta to pick a job, then run it with etl_nightly
# See Also: (ds* scripts for inside the docker container)
# dsinstall
# dsetl
# dsetl_nightly

if [ "$IS_DOCKER_LOCAL" != "1" ]; then
    echo "Must be run from inside the docker container."
    exit
fi

pushd ~/data_services/etl/warehouse

JOB=`find . -name '*.py' | grep "$1" | selecta | sed -e 's|^[/.]*||'`
shift

# Always echo the shell command
# No need for \033[1F, or rather it won't help: selecta messes up the screenshot
echo '#' python etl_nightly.py --retry_count 1 --job "$JOB" $@
python etl_nightly.py --retry_count 1 --job "$JOB" $@
popd
