#!/bin/bash
# dsetl_nightly - run specific job (TEMP: currently hardcoded to d_rac_customers lol)
# See Also: (ds* scripts for inside the docker container)
# dsinstall
# dsetl
# dsetl_nightly
if [ `hostname` != 'e4ecac526fec' ]; then
    echo "Must be run from inside the docker container."
    exit
fi

if [ -z "$JOB" ]; then
    echo 'ERROR: $JOB is not set.'
    exit
fi

echo "# time python etl_nightly.py --job $JOB"
time python etl_nightly.py --job $JOB
