#!/bin/bash
# dsetl - selecta to pick a job, then run it with etl_nightly
# See Also: (ds* scripts for inside the docker container)
# dsinstall
# dsetl
# dsetl_nightly

if [ `hostname` != 'e4ecac526fec' ]; then
    echo "Must be run from inside the docker container."
    exit
fi

pushd ~/data_services/etl/warehouse
JOB=`find . -name '*.py' | selecta | sed -e 's|^[/.]*||'`
echo '#' python etl_nightly.py --job "$JOB"
python etl_nightly.py --job "$JOB"
popd
