#!/bin/bash
# dsinstall - run python setup of dataservices package
# See Also: (ds* scripts for inside the docker container)
# dsinstall
# dsetl
# dsetl_nightly
if [ `uname -s` != 'Linux' ]; then
    echo "Must be run from inside the docker container."
    exit
fi

echo -e "\033[36m(cd ~/data_services_package && python setup.py clean && python setup.py install)\033[0m"
(cd ~/data_services_package && python setup.py clean && python setup.py install)
