#!/usr/bin/env ruby
# dsv-error-counts <table> - get validation error counts from <table>_migration_check
# tl;dr It's "this field is bad, here's the count" for all bad fields
require "optimist"

opts = Optimist.options do
  opt :csv, "Get query results as CSV", type: :boolean, default: false
  opt :finance, "Use snowflake_finance warehouse", type: :boolean, default: false
  opt :table, "Table name (uses ARGV.last if omitted)", type: :string, required: false
  opt :debug, "Debug mode (gets chatty)", type: :boolean, default: false
end
table = opts[:table] || ARGV[0] || `get-ds-table`.strip
Optimist::die "Must specify a table name." if table&.empty?

warehouse = if opts[:finance]
               "snowflake_finance"
             else
               "snowflake"
             end

table = "#{table}_migration_check"

query = <<SQL
    SELECT field_name AS #{table}_field, COUNT(*) FROM #{table} GROUP BY 1 ORDER BY 2 DESC
SQL

query = query.each_line.map(&:strip).to_a.join(" ")

command = %Q|dsquery #{opts[:csv] ? '--csv ' : ''}--warehouse #{warehouse} --query "#{query}"|
puts command if opts[:debug]
system command
