#!/usr/bin/env ruby
# dsv-error-counts <table> - get validation error counts from <table>_migration_check
# tl;dr It's "this field is bad, here's the count" for all bad fields
require "optimist"

opts = Optimist.options do
  opt :csv, type: :boolean, default: false
  opt :finance, "Use snowflake_finance warehouse", type: :boolean, default: false
end
table = ARGV[0]
Optimist::die "Must specify a table name." if !table || table.empty?

warehouse = if opts[:finance]
               "snowflake_finance"
             else
               "snowflake"
             end

table = "#{table}_migration_check"

query = <<SQL
    SELECT field_name AS #{table}_field, COUNT(*) FROM #{table} GROUP BY 1 ORDER BY 2 DESC
SQL

query = query.each_line.map(&:strip).to_a.join(" ")

command = %Q|dsquery #{opts[:csv] ? '--csv ' : ''}--warehouse #{warehouse} --query "#{query}"|
puts command
system command
