#!/bin/sh
echo "Comparing new-$1 to $1..."
echo "======================================================================"
echo "new-$1"
fig2 "new-$1" Test Message

echo "$1"
fig2 "$1" Test Message

ls -la "new-$1.flf" "$1.flf"
echo "======================================================================"
