#!/bin/bash
# gas - git add-script, prompt to commit.
# gas -m "[msg]" to automatically commit.
# gas -p to prompt.
# git add-script echoes the command for us
git add-script

if [ "$1" == "-p" ]; then
    echo -n "Enter commit message: "
    read msg
elif [ "$1" == "-m" ]; then
    msg="$2"
fi

echo "git commit -m \"$msg\""
git commit -m "$msg"
