#!/bin/bash
# gcs - "git commit script"

if [ `uname -s` == 'Darwin' ]; then
    WAREHOUSE=/Users/david.brady/acima/devel/data_services/etl/warehouse
else
    WAREHOUSE=/root/data_services/etl/warehouse
fi

echo -e "\033[36msnow-commit-ds-script \"$*\"\033[0m"
snow-commit-ds-script "$*"
