#!/usr/bin/env ruby
# get-gsheet-id [<job_file.py>] - get gsheet id from job config
require 'json'

def get_script
  return $get_script if $get_script
  $get_script = ARGV.first || `get-ds-script`.strip || ENV['SCRIPT']
end

script = (ARGV.first || get_script).gsub(%r|/|, '.').sub(/\.py$/, '')

config = File.read(File.expand_path("~/data_services/etl/warehouse/finance/config/etl_nightly_config.json"))

json = JSON.parse(config)

puts json["jobs"][script]["google_sheet_id"]
