#!/bin/bash
# gh - Open the github homepage for the current project
echo "Opening the github homepage for this project..."
if [ 'Darwin' == `uname -a | awk '{print $1}'` ]; then
    open http://$(git remote show origin | grep "Fetch URL" | awk '{ print $3 }' | cut -d @ -f 2 | sed -e 's/:/\//')
else
    # In theory, sensible-browser is more correct than xdg-open, but in practice
    # it opens Mozilla Firefox even if chromium is my default browser
    xdg-open https://$(git remote show origin | grep "Fetch URL" | awk '{ print $3 }' | cut -d @ -f 2 | sed -e 's/:/\//') &> /dev/null
fi
