#!/usr/bin/env ruby
# gh-get-pr-title - get the title of a specific pull request
require "colorize"
require "octokit"
require "optimist"
require_relative "bin/dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  opt_flag :link

  def run
    @opts = Optimist.options do
      opt :debug, "Print extra debug info", default: false
      opt :pretend, "Print commands but do not run them", default: false
      opt :verbose, "Run with verbose output (overrides --quiet)", default: false
      opt :quiet, "Run with minimal output", default: false
      opt :link, "Print the PR link", default: false
    end
    opts[:quiet] = !opts[:verbose] if opts[:verbose_given]
    puts opts.inspect if opts[:debug]

    access_token = github_pat

    client = Octokit::Client.new(access_token: access_token)

    repo_orig, pr_number = if ARGV.size.zero?
                        get_repo_and_pr_from_branch
                      elsif ARGV.size == 1
                        [get_repo_and_pr_from_branch.first, ARGV.first]
                      else
                        ARGV
                      end

    # TODO: get_repo needs to return user/repo format as well
    repo = "acima-credit/#{repo_orig}"

    if debug?
      puts "repo: #{repo}"
      puts "pr_number: #{pr_number}"
    end

    pull_request = client.pull_request(repo, pr_number)

    puts pull_request.title
  end
end

# Run the application
Application.new.run
