#!/usr/bin/env ruby
# gh-update-pats <new_pat> - Update github PATs
#
# This script will update ~/.bundle/config and
# ~/acima/shared/.bundle/config. Everything under acima should be symlinking its
# .bundle/config to the shared acima location.

require "colorize"
require "optimist"
require_relative "lib/dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli
  attr_reader :pat

  # Update these if you don't put your code where I do.
  ACIMA_SHARED_CONFIG_FOLDER = "~/acima/shared/.bundle"

  def run
    @opts = Optimist.options do
      banner <<BANNER
gh-update-pats <new_pat> - Update github PATs

This fixes this error:

```
Fetching source index from https://rubygems.pkg.github.com/acima-credit/

#{'Bad username or password for https://dbrady@rubygems.pkg.github.com/acima-credit/.'.red}
#{'Please double-check your credentials and correct them.'.red}
```

1. Go to github, click on your portrait in the upper right, click Settings. Or
   click here: https://github.com/settings/profile

2. In the left sidebar click < > Developer Settings

3. On the new page, in the left sidebar, click Personal access tokens to open
   a dropdown and choose Tokens (classic)

4. In the upper right click the button that says Generate New Token

5. If you get challenged for a 2FA here, the code you want is in Google
   Authenticator, not Duo

6. These permissions are documented in the onboarding wiki:

   #{'repo, workflow, write:packages, admin:org'.cyan}

7. #{'WATCH OUT'.bold.white.on_red}: Click the Generate New Token button. You'll go back to the
   list of tokens, there will be a green box with your new token in it, right
   below a blue box saying "Make sure to copy this token... you won't see this
   again!". #{'COPY THIS BEFORE YOU CONFIGURE SSO! THEY ARE NOT KIDDING.'.bold.red}

8. #{'SRSLY. COPY THE TOKEN NOW.'.bold.red}

9. Click Configure SSO to open the list of orgs. Click "Authorize" next to
   acima-credit. THIS WILL REDIRECT TO YOU AWAY FROM THIS PAGE so I really hope
   you copied the token when I told you to. If you did not, this was all just for
   practice. Go back to step 7, you silly goose.

10. Open .bundle/config and update the BUNDLE_HTTPS line with the correct
   PAT. THIS SCRIPT WILL DO THIS PART FOR YOU, BUT YOU NEED TO DO THE REST FIRST.

Options:
BANNER
      opt :debug, "Print extra debug info", default: false
      opt :pretend, "Print commands but do not run them", default: false
      opt :verbose, "Run with verbose output (overrides --quiet)", default: false
      opt :quiet, "Run with minimal output", default: false
    end
    opts[:quiet] = !opts[:verbose] if opts[:verbose_given]
    puts opts.inspect if opts[:debug]

    Optimist.educate if ARGV.empty?

    @pat = ARGV.first

    raise "You must provide a github personal access token!" unless pat =~ /^ghp_/

    # PATHS TO UPDATE This used to be a bigass hash of locations. Refactoring to
    # symlink collapsed all the project paths, yay.
    files = [
      # My root config for things that don't follow protocol
      "~/.bundle/config",

      # My core symlink auth location
      "#{ACIMA_SHARED_CONFIG_FOLDER}/config",
    ].map {|file| File.expand_path(file)}

    # TOKENS TO SET
    tokens = [
      "BUNDLE_RUBYGEMS__PKG__GITHUB__COM",
      "BUNDLE_HTTPS://RUBYGEMS__PKG__GITHUB__COM/ACIMA___CREDIT/",
      "BUNDLE_GEMS__KARAFKA__IO:",
    ]

    files.each do |file|
      puts file
      lines = File.readlines(File.expand_path(file)).map(&:strip)
      tokens.each do |token|
        lines.reject! {|line| line =~ /^\s*#{token}/}
        lines << "#{token}: #{pat}"
      end
      puts lines
      puts "##############"

      timestamp = Time.now.strftime("%Y%m%s%H%M%S")
      backupfile = "#{file}.#{timestamp}"
      run_command "cp #{file} #{backupfile}"
      File.open(file, "w") {|fp| fp.puts lines }
      puts "Wrote #{file}"
    end
  end

end


if __FILE__ == $0
  Application.new.run
end
