#!/usr/bin/env ruby
# git open-pr - open pull request previously set with git-set-pr

if `hostname`.strip != 'MAC0825PRO.local'
  raise "Can't access settings file from Docker. Run on OSX, please."
end

require 'yaml'

settings_file = File.expand_path("~/.git-set-pr.yml")

pwd = Dir.pwd
current_branch = `git current-branch`.strip

pr = YAML.load_file(settings_file).fetch(pwd, {}).fetch(current_branch)

path = `git remote show origin | grep "Fetch URL" | awk '{ print $3 }'`
    .sub(/^.+@.+:/, '')
    .sub(/\.git$/, '')
    .strip

url = "https://github.com/#{path}/pull/#{pr}"
puts "PR URL: #{url}"

def osx?
  `uname -s`.strip == 'Darwin'
end

if osx?
  system "open #{url}"
else
  # In theory, sensible-browser is more correct than xdg-open, but in practice
  # it opens Mozilla Firefox even if chromium is my default browser
  system "xdg-open #{url} &> /dev/null"
end
