#!/bin/bash
# git add-new <file> [<file2> [...]]

# commify args. `git add-new a b c d` -> "a, b, c, d"
# first time through loop, files and glue expand to empty string.
for i in "$@"; do
    files="$files$glue$i"
    glue=', '
done

# TODO: Do a git commit --amend if
# - file I'm adding is already in git
# - the only modified file is the file I'm adding
# - the last commit was the add-new for that file
if ! git-isclean; then
    echo "You have modified files and/or something alreday staged. Commit or stash other changes first. Or manually add them with"
    echo "git add $@"
    echo "git commit -m \"Add $files\""
    exit -1
fi

# This will show new files
# git ls-files --others --exclude-standard

echo git add "$@"
git add "$@"

echo git commit -m "Add $files"
git commit -m "Add $files"
