#!/usr/bin/env ruby
# git create-pr - open a browser on github to create a PR for this branch
require "cgi"
require "colorize"
require "optimist"
require "yaml"
String.disable_colorization unless $stdout.tty?

opts = Optimist.options do
  opt :debug, "Print extra debug info", default: false
  opt :pretend, "Show create pr link but do not open a browser", default: false

  opt :title, "Title (if omitted, tries to infer from branch)", type: :string
end
puts opts.inspect if opts[:debug]


def osx?
  `uname -s`.strip == "Darwin"
end

# ROOT_URL = "https://github.com/acima-credit/merchant_portal/pull/new/"
current_branch = `git current-branch`.strip
main_branch = `git parent-branch`.strip
main_branch = `git main-branch`.strip if main_branch.empty?
url = "https://github.com/acima-credit/merchant_portal/compare/#{main_branch}...#{current_branch}?expand=1"

# Set the title of the PR if possible
ticket_id = current_branch.split(%r|/|).find {|segment| segment =~ /^[A-Z]+-\d+$/ }
branch_title = if opts[:title_given]
                 opts[:title]
               else
                 current_branch         # "dbrady/CREDIT-10/these-are-my-pants"
                   .split(ticket_id)    # ["dbrady/", "/these-are-my-pants"]
                   .last                # "/these-are-my-pants"
                   .sub(%r|^/|, "")     # "these-are-my-pants
                   .gsub(/[-_]/, " ")   # "these are my pants"
                   .capitalize          # "These are my pants"
               end

title = "[#{ticket_id}] #{branch_title}"
escaped_title = CGI::escape(title)
url += "&title=#{escaped_title}"

if opts[:debug]
  puts "ticket_id: #{ticket_id}"
  puts "title: #{title}"
  puts "escaped_title: #{escaped_title}"
  puts "url: #{url}" if opts[:debug]
end


if osx?
  puts url.cyan
  cmd = "open '#{url}'"
  system cmd unless opts[:pretend]
else
  # next time I'm on linux, test this out with e.g., xdg-open
end
