#!/bin/bash
if ! git-isclean; then
    echo "You have modified files and/or something alreday staged. Commit or stash other changes first. Aborting."
    exit -1
fi

# commify args. `git add-new a b c d` -> "a, b, c, d"
# first time through loop, files and glue expand to empty string.
for i in $@; do
    files="$files$glue$i"
    glue=', '
done

echo git add $@
git add $@

echo git commit -m "Add $files"
git commit -m "Add $files"
