#!/usr/bin/env ruby
# git set-pr <number> - associate PR with current branch
require "colorize"
require "extralite"
require "optimist"

# TODO: Convert from bare sql to Sequel or AR

require_relative "dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  opt_flag :slork

  DATABASE_PATH = File.expand_path('~/bin/db/git-settings.db')

  def db
    @db ||= Extralite::Database.new(DATABASE_PATH)
  end

  def run
    @opts = Optimist.options do
      opt :debug, "Print extra debug info", default: false
      opt :pretend, "Print commands but do not run them", default: false
      opt :verbose, "Run with verbose output (overrides --quiet)", default: false
      opt :quiet, "Run with minimal output", default: false

      opt :slork, "Update slork", default: true
    end
    opts[:quiet] = !opts[:verbose] if opts[:verbose_given]
    puts opts.inspect if opts[:debug]

    pr = ARGV.first.to_i
    Optimist::die("Must supply a PR id") unless pr && pr.to_i > 0

    # Associate repo and branch --> pr
    repo = git_repo_for(Dir.pwd)
    current_branch = `git current-branch`.strip

    # BEGIN save to db
    # TODO: Convert to Sequel? And then
    # pr = PrHistory.where(repo:, branch: current_branch, deleted_at: nil).order(:updated_at.desc).first_or_create
    # pr.pr = pr
    # pr.save
    query = "DELETE FROM pr_history WHERE repo='#{repo}' AND branch='#{current_branch}'"
    puts query.cyan if debug?
    db.execute query unless pretend?

    now = Time.now.strftime("%F %T")
    query = "INSERT INTO pr_history (repo, branch, pr, created_at, updated_at, deleted_at) VALUES ('#{repo}', '#{current_branch}', #{pr}, '#{now}', '#{now}', NULL)"
    puts query.cyan if debug?
    db.execute query unless pretend?
    # END save to db

    puts "Recorded. Branch '#{current_branch}' is PR number #{pr}."

    if slork?
      board, ticket = get_board_and_ticket_from_branch
      Optimist::die("Couldn't figure out board-ticket from branch") unless board && ticket
      run_command "slork set-pr --board=#{board} --ticket=#{ticket} --pr=#{pr}"
    end
  end
end


if __FILE__ == $0
  Application.new.run
end
