#!/usr/bin/env ruby
# frozen_string_literal: true
# git-rebasable - return true unless I have flagged the branch as merge-only in
# slorks
#
# IT JUST CHECKS MY FLAG. IT DOES NOT TRY TO CALCULATE IF A REBASE IS CONFLICTED.
# (The flag is in ~/bin/db/git-settings.db. SELECT branch, rebasable FROM slorks)
#
# Example:
# git rebasable && git rebase -i master || git merge master
require "colorize"
require "extralite"
require "optimist"
$:.unshift(File.expand_path("~/bin/lib"))
require "dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  DATABASE_PATH = File.expand_path('~/bin/db/git-settings.db')

  def db
    @db ||= Extralite::Database.new(DATABASE_PATH)
  end

  def run
    @opts = Optimist.options do
      banner <<BANNER
git-rebasable - return true unless I have flagged the branch as merge-only in
slorks

IT JUST CHECKS MY FLAG. IT DOES NOT TRY TO CALCULATE IF A REBASE IS CONFLICTED.
(The flag is in ~/bin/db/git-settings.db. SELECT rebasable FROM slorks)

Example:
  git rebasable
  git rebasable <branch>
  git rebasable && git rebase -i master || git merge master

Options:
BANNER
      opt :debug, "Print extra debug info", short: :d, default: false
      opt :pretend, "Print commands but do not run them", short: :p, default: false
      opt :verbose, "Run with verbose output (overrides --quiet)", short: :v, default: false
      opt :quiet, "Run with minimal output", short: :q, default: false

      # @ignore_invalid_options = true # no error given if you call this with other options (good for passthru)

      # plural types or type in [array] means multiple VALUES for this
      #   arg, but --arg can only appear once

      # multi: true means the --arg can appear multiple times, and
      #   each element will be of the type indicated.

      # If you specify both a plural type AND multi, you will get an
      #   array of arrays. See "batches" below.
      #
      #   opt :sizes, type: :ints
      #   opt :names, default: [String]
      #   opt :file, type: :string, multi: true
      #   opt :batches, type: :strings, multi: true
      #
      # How you would call these:
      #   --sizes 8 9 9                   # [8, 9, 9]
      #   --names Alice Bob Carol         # ["Alice", "Bob", "Carol"]
      #   --file=1.txt --file=2.txt       # ["1.txt", "2.txt"]
      #   --batches a b c --batches d e   # [["a","b","c"], ["d","e"]]

      # CONSTRAINTS: See https://www.manageiq.org/optimist/
      #
      # depends : # You may specify AT MOST one
      # conflicts :cat, :dog, :rat     # You may specify at most one
      # either :left, :right, :center  # You MUST specify EXACTLY one
    end
    opts[:quiet] = !opts[:verbose] if opts[:verbose_given]
    if debug?
      puts opts.sort.to_h.inspect
      puts "opt_flags: (#{opt_flags.size})"
      opt_flags.each do |flag|
        flag_method = "#{flag}?"
        puts "#{flag}: #{public_send(flag_method).inspect}"
      end
      puts "opt_readers: (#{opt_readers.size})"
      opt_readers.each do |reader|
        puts "#{reader}: #{public_send(reader).inspect}"
      end
    end

    run!
  end

  # APP CODE GOES HERE
  def run!
    branch = ARGV.first ? ARGV.first : git_current_branch

    # TODO: confirm repo, check to make sure only one slork is found, promote to new-ruby template?

    # Query the database for the rebasable status
    values = query("SELECT board, ticket, rebasable FROM slorks WHERE branch = '#{branch}' AND deleted_at IS NULL")
    rebasable = if values.size == 1
                  values.first[:rebasable]
                elsif values.size.zero?
                  1 # default to true, it IS rebasable
                else
                  puts "Expected to find at most 1 record, but got #{values.size}:"
                  values.each do |value|
                    puts "#{value[:board]}-#{value[:ticket]}: #{value[:title]}: #{value[:rebasable]}"
                  end
                  exit
                end
    puts "rebasable: #{rebasable.inspect}" if debug?
    exit rebasable.zero? ? 1 : 0
  end

  def query(sql)
    puts sql.cyan if debug?
    db.query_hash(sql)
  end

end


if __FILE__ == $0
  Application.new.run
end
