#!/usr/bin/env ruby
# git-home-url - Display the github homepage URL for the current project
require "colorize"

def osx?
  `uname -s`.strip == 'Darwin'
end

url=`git remote get-url origin`

# url can be of the form git@server (for ssh mode) or https:// for web mode
# if it's http mode we're already done; if ssh we need to massage it
if url !~ /^http/
  url = url.sub(/:/, "/").sub(/^.*@/, "https://")
end

url = url.sub(/.git$/, '').strip

# Tell user what we're gonna open
puts url
