#!/usr/bin/env ruby
# git-open-jira -
require "colorize"
require "optimist"
require_relative "dbrady_cli"
String.disable_colorization unless $stdout.tty?

require_relative "dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  attr_reader :opts


  def debug?
    opts[:debug]
  end

  def run
    @opts = Optimist.options do
      opt :debug, "Print extra debug info", default: false
    end
    puts opts.inspect if opts[:debug]

    run_command "open #{jira_url}"
  end
end

if __FILE__ == $0
  Application.new.run
end
