#!/usr/bin/env ruby
# frozen_string_literal: true
# git rac <file(s)> - review and commit
require "colorize"
require "optimist"
$:.unshift(File.expand_path("~/bin/lib"))
require "dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  opt_flag :all

  def run
    @opts = Optimist.options do
      banner <<BANNER
git rac <file(s)> - review and commit

Options:
BANNER
      opt :all, "Automatically include all modified files", short: :a, default: false
      opt :debug, "Print extra debug info", short: :d, default: false
      opt :pretend, "Print commands but do not run them", short: :p, default: false
      opt :quiet, "Run with minimal output", short: :q, default: false
      opt :verbose, "Run with verbose output (overrides --quiet)", short: :v, default: false
    end
    opts[:quiet] = !opts[:verbose] if opts[:verbose_given]
    dump_opts if debug?

    run!
  end

  def run!
    files = if all?
              get_command_output_lines('git modified', quiet: true).map(&:inspect).join(' ')
            else
              ARGV.map(&:inspect) * ' '
            end
    run_command "git add #{files}"
    if run_command('git commit -v')
      puts 'Committed.'.light_green
    else
      puts 'Resetting file'
      # TODO: don't reset files if they were already staged?
      run_command "git reset #{files}"
    end
  end

end


if __FILE__ == $0
  Application.new.run
end
