#!/usr/bin/env ruby
# git set-pr <number>
require 'yaml'

if `hostname`.strip != 'MAC0825PRO.local'
  raise "Can't access settings file from Docker. Run on OSX, please."
end

unless ARGV.size == 1 && ARGV.first.to_i > 0
  puts "PR number '#{ARGV.first}' does not look like a PR number"
  exit -1
end

settings_file = File.expand_path("~/.git-set-pr.yml")

settings = if File.exist? settings_file
             YAML.load_file(settings_file)
           end
settings ||= {}

pwd = Dir.pwd
current_branch = `git current-branch`.strip

settings[pwd] ||= {}

settings[pwd][current_branch] = ARGV.first.to_i

File.open(settings_file, "w") do |fp|
  fp.puts settings.to_yaml
end
