#!/bin/sh
# Pulls the current branch from the remote server (default origin)
branch=$(git branch 2>/dev/null | grep ^\* | sed -e s/^\*[[:space:]]// )
[ x$1 != x ] && remote=$1 || remote=origin
echo "git pull ${remote} ${branch}"
git pull ${remote} ${branch}
