#!/usr/bin/env ruby
# git-home - Open the github homepage for the current project
require "colorize"

def osx?
  `uname -s`.strip == 'Darwin'
end

puts "Opening the github homepage for this project: "

url = `git-home-url`.strip

def osx?
  `uname -s`.strip == 'Darwin'
end

puts url.on_green

if osx?
  system "open #{url}"
else
  # In theory, sensible-browser is more correct than xdg-open, but in practice
  # it opens Mozilla Firefox even if chromium is my default browser
  system "xdg-open #{url} &> /dev/null"
end
