#!/bin/bash
#!/bin/bash

if [[ "$1" != "-q" && "$1" != "--quiet" ]]; then
    echo -e "\033[36mgit branch -a | grep -vE '^[[:space:]]*remotes/'\033[0m"
fi
git branch -a | grep -vE '^[[:space:]]*remotes/'
