#!/usr/bin/env ruby
# git-main - identify and check out main branch for this repo

def config_filepath
  File.join(Dir.pwd, ".git/", "config")
end

# The home/main branch for a repo is usually the first branch identified as the merge branch.
def first_merge
  IO.readlines(config_filepath).detect {|line| line =~ /^\s+merge = / }.split(/ = /)[1].split(/\//).last
end

cmd = "git checkout #{first_merge}"
puts cmd
system cmd
