#!/bin/bash
SCRIPT=`get-ds-script`

if [ "$SCRIPT" == "" ]; then
    echo 'No $SCRIPT var found. Please export SCRIPT=<script> before running this script.'
else
    echo git add $SCRIPT
    git add $SCRIPT
fi
