#!/usr/bin/env ruby
# git-main - identify and return the main branch for this repo

require 'yaml'

def cache_file
  File.expand_path("~/.git-main-branches.yml")
end

def cache
  @cache ||= if !File.exist?(cache_file)
                    {}
                  else
                    YAML.load_file(cache_file)
                  end
end

def save_cache
  File.open(cache_file, "w") do |fp|
    fp.puts cache.to_yaml
  end
end

def cache_lookup(dir)
  cache[dir]
end

def cache_branch(dir, branch)
  cache[dir] = branch
  save_cache
end

def get_main_branch_from_remote
  `git remote show origin`.each_line.to_a.grep(/^\s*HEAD branch:\s+/).first.split(/: /).last.strip
end

dir = Dir.pwd

if ARGV.include?("-f") || !cache_lookup(dir)
  branch = get_main_branch_from_remote
  cache_branch dir, branch
end

puts cache_lookup(dir)
