#!/usr/bin/env ruby
# git-home - Open the github homepage for the current project
puts "Opening the github homepage for this project: "
url=`git remote show origin | grep "Fetch URL" | awk '{ print $3 }'`

def osx?
  `uname -s`.strip == 'Darwin'
end

# url can be of the form git@server (for ssh mode) or https:// for web mode
# if it's http mode we're already done; if ssh we need to massage it
if url !~ /^http/
  url = url.sub(/:/, "/").sub(/^.*@/, "https://")
end

url = url.sub(/.git$/, '').strip

# Tell user what we're gonna open
puts "\x1b[1;37;42m#{url}\x1b[0m"

if osx?
  system "open #{url}"
else
  # In theory, sensible-browser is more correct than xdg-open, but in practice
  # it opens Mozilla Firefox even if chromium is my default browser
  system "xdg-open #{url} &> /dev/null"
end
