#!/bin/sh
curbranch=$(git-currentbranch)
echo "Pulling updates into all local branches"
echo "You are in $curbranch"

for b in $(git branch|sed -e 's/\*//'); do
    echo "checking out $b..."
    git checkout $b
    echo "pulling updates from $b..."
    git pull
done

echo "Returning to $curbranch"
git checkout $curbranch

