#!/bin/bash
# git addandcommit - add 1 file and commit it with a message

usage() {
    echo "git addandcommit - add 1 file and commit it"
    echo "Usage:"
    echo "    git addandcommit <file> <message>"
}

if [ $1 == "-?" ]; then
    usage
    exit -1
fi

if [ $# -lt 2 ]; then
    echo "$# of 2 arguments given; Must supply file and message arguments"
    usage
    exit -1
fi

echo

# TODO: make sure no files are currently staged
file=$1
shift
message=$@
echo "git add \"$file\""
git add "$file"
echo "git commit -m \"$message\""
git commit -m "$message"
