#!/usr/bin/env ruby
# git-slam - take a branch from "ready to review" through to "here's your PR"
#
#
require "colorize"
require "optimist"
require_relative "dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  def run
    @opts = Optimist.options do
      banner <<BANNER
This script is currently documentation checklist only. SO GO DO THIS, OKAY?
  git isclean                       to ensure there are no outstanding changes
  git-rubocop                       to run rubocop on files-changed
  git-cram                          to push the branch up with --set-origin
  mp-make-github-pr-text | pbcopy   to put the PR template in your clipboard
  git-create-pr                     to open the PR creation page
  git-set-pr <pr>                   to record the PR number after creation
  @robby assign <pr>

Options:
BANNER
      opt :debug, "Print extra debug info", default: false
      opt :pretend, "Print commands but do not run them", default: false
      opt :verbose, "Run with verbose output (overrides --quiet)", default: false
      opt :quiet, "Run with minimal output", default: false
    end
    opts[:quiet] = !opts[:verbose] if opts[:verbose_given]
    puts opts.inspect if opts[:debug]

    # APP CODE GOES HERE
    puts "This script is currently documentation checklist only. RERUN WITH --help AND GO DO THAT, OKAY?"
  end

end


if __FILE__ == $0
  Application.new.run
end
