#!/usr/bin/env ruby
# git get-pr - display pull request (previously set with git-set-pr)

require 'yaml'

# Return true if path contains a .git/ folder or a .git file (specific instance of a submodule)#
# Duplicate code in git-branch-history and git-log-branch. Is it make-a-git-tools-gem o'clock yet?
def is_git_repo?(path)
  File.exist?(File.join(path, '.git'))
end

# Walk up file tree looking for a .git folder
# Duplicate code in git-branch-history and git-log-branch. Is it make-a-git-tools-gem o'clock yet?
def git_repo_for(path)
  starting_path = last_path = path

  while !path.empty?
    return path if is_git_repo?(path)
    last_path, path = path, File.split(path).first
    raise " FIGURE OUT PATH FOR #{starting_path.inspect}" if last_path == path
  end
end

settings_file = File.expand_path("~/.git-set-pr.yml")

dir = git_repo_for(Dir.pwd)
current_branch = `git current-branch`.strip
pr = YAML.load_file(settings_file)[dir][current_branch]

if pr.nil?
  $stderr.puts "No PR for #{dir}"
  exit -1
end

path = `git remote get-url origin`.strip

puts "https://github.com/#{path}/pull/#{pr}"
