#!/bin/sh
# git current-branch [-p] - display current branch name
#
# -p - copy to pasteboard/clipboard instead of display

if [ "$1" == "-p" ]; then
    git branch --show-current | pbcopy
else
    git branch --show-current
fi
