#!/bin/bash
# git restore-all - run git restore on all files currently modified in branch. WILL NOT RESET STAGED CHANGES.
echo -e "\033[36mgit modified $@ | xargs git restore\033[0m"
git modified | xargs git restore
