#!/bin/bash
# gopto - "git hop to" branch
# TL;dr go master && remaster && git checkout branch && bundle && remigrate
echo git main
git main

echo remaster
remaster

echo 'git checkout $(git branch | grep "$1" | sed -e 's/^\* //' | selecta)'
git checkout $(git branch | grep "$1" | sed -e 's/^\* //' | selecta)

echo bundle install
bundle install

echo remigrate
remigrate
