#!/bin/bash
# restore etl_nightl.py if it's been patched
echo -e "\033[36m(cd ~/data_services/etl/warehouse/finance && git restore etl_nightly.py)\033[0m"
(cd ~/data_services/etl/warehouse/finance && git restore etl_nightly.py)
