#!/bin/bash
# restore etl_nightl.py if it's been patched
echo -e "\033[36m(cd ~/data_services/etl/warehouse/finance && git restore etl_nightly.py config/etl_nightly_config.json)\033[0m"
(cd ~/data_services/etl/warehouse/finance && git restore etl_nightly.py config/etl_nightly_config.json)
