#!/bin/bash
# grs - git rebase --skip

if [[ -d .git/rebase-apply ]] ; then
    echo "Press ENTER to git rebase --skip, or hit Ctrl-C to abort:"
    read
    echo git rebase --skip
    git rebase --skip
else
    echo "\033[31;40mCannot git rebase --skip: .git/rebase-apply folder does not exist"
    exit 1
fi
