#!/usr/bin/env ruby
# highlight-lines <regex> - Like grep -E --color=always except highlight the entire line instead of just the match.
# cat file.txt | highlight-lines "pants"
# highlight-lines "pants" file.txt

require "colorize"
require "optimist"

opts = Optimist.options do
  banner <<HALP
highlight-lines [options] <regex> [<file> [<file2> [...]]]
cat <file> | highlight-lines [options] <regex>
HALP

  opt :debug, "Print extra debug info", default: false
  opt :color, "Color name to use, e.g red, green, light_black", default: "green"
  opt :"ignore-case", "Ignore case", default: false
end
puts opts.inspect if opts[:debug]

options = 0
options |= Regexp::IGNORECASE if opts[:"ignore-case"]

regex = Regexp.new(ARGV.shift) # ARGV.first but get rid of it so

ARGF.each_line do |line|
  line.rstrip!
  color = (line =~ regex ? opts[:color] : "normal").to_sym
  puts line.colorize(color)
end
