#!/usr/bin/env ruby
require_relative "hl"

if !recent_exists?
  puts "No recent file exists, setting to 4..."
  set_light_level 4
  write_recent 4
  exit 0
end

levels = (ARGV.first || 1).to_i

old_level = load_recent

new_level = clamp(old_level + levels, MIN_LEVEL, MAX_LEVEL+1)

if old_level == 0
  puts "Already at 0, doing nothing"
elsif new_level == MAX_LEVEL+1
  puts "Turning lights off"
  write_recent 0
  set_light_level 0
else
  puts "At #{old_level}, dimming to #{new_level}"
  write_recent new_level
  set_light_level new_level
end
