#!/usr/bin/env ruby
# This is sad. Honestly the old bash code was almost more readable. Why do I
# even computer
require_relative "hl"

if !recent_exists?
   puts "No recent file exists, setting to 4..."
   set_light_level 4
   write_recent 4
   exit 0
end

levels = (ARGV.first || 1).to_i

old_level = load_recent

new_level = if old_level == 0
              clamp((MAX_LEVEL+1) - levels, MIN_LEVEL, MAX_LEVEL)
            else
              clamp(old_level - levels, MIN_LEVEL, MAX_LEVEL)
            end

# puts "levels: #{levels}"
# puts "new_level: #{new_level}"
# puts "old_level: #{old_level}"

new_level = 1 if old_level > 0 && new_level < 1

if old_level == 1
  puts "Already at h1, doing nothing"
elsif old_level == 0
  puts "Turning lights on to level #{new_level}"
  write_recent new_level
  set_light_level new_level
else
  puts "At #{old_level}, brightening to #{new_level}"
  write_recent new_level
  set_light_level new_level
end
