#!/bin/bash
# hueoff <time> - shut off lamps (gently)
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |
#
# Office Lamp Arrangement 2018
# 4 - Office Spotlight
# 5 - Main Floor Office Lightstrip
# 9 - Upstairs Office Lightstrip
# 10 - Office Light Fixture (North Bulb)
# 11 - Office Light Fixture (South Bulb)

if [ $# == 0 ]; then
    DELAY=10
else
    DELAY=$1
fi
TTIME="${DELAY}0"

TTIME=0

# bring lights down softly
for lamp in 1 2 3 4 5 7 8 9 10 11; do
    echo $lamp
# for lamp in 4 9 10 11; do
    # curl -X PUT "http://$HUE_IP/api/$HUE/lights/$lamp/state" -d "{\"bri\":0, \"transitiontime\":$TTIME}" 2>/dev/null > /dev/null
    curl -X PUT "http://$HUE_IP/api/$HUE/lights/$lamp/state" -d "{\"bri\":0, \"transitiontime\":0}" 2>/dev/null > /dev/null
done
sleep $DELAY

# TODO: Find a way to embed this all in one call? Bet it can be done with a jquery compound body posted directly to /lights/
for lamp in 1 2 3 4 5 7 8 9 10 11; do
    # for lamp in 4 9 10 11; do
    echo $lamp
    curl -X PUT "http://$HUE_IP/api/$HUE/lights/$lamp/state" -d '{"on":false, "transitiontime":0}' 2>/dev/null > /dev/null
done
