#!/bin/sh
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |
#
# Office Lamp Arrangement 2018
# 4 - Office Spotlight
# 9 - Office Lightstrip
# 10 - Office Light Fixture (North Bulb)
# 11 - Office Light Fixture (South Bulb)

for lamp in 4 9 10 11; do
    curl -X PUT "http://$HUE_IP/api/$HUE/lights/$lamp/state" -d '{"on":true, "bri": 254, "hue": 14910, "sat": 144, "transitiontime":0}' 2>/dev/null > /dev/null
done

# With the "conce
  # "11": {
  #   "state": {"on": true, "bri": 254, "hue": 14910, "sat": 144,
  #     "effect": "none",
  #     "xy": [
  #       0.4596,
  #       0.4105
  #     ],
  #     "ct": 370,
  #     "alert": "none",
  #     "colormode": "ct",
  #     "reachable": true
  #   },
  #   "swupdate": {
  #     "state": "readytoinstall",
  #     "lastinstall": null
  #   },
  #   "type": "Extended color light",
  #   "name": "Office 2",
  #   "modelid": "LCT007",
  #   "manufacturername": "Philips",
  #   "uniqueid": "00:17:88:01:10:4a:7b:94-0b",
  #   "swversion": "5.38.1.14919"
  # }
