#!/bin/sh
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |

curl -X PUT "http://192.168.0.66/api/$HUE/lights/1/state" -d '{"on":true, "bri":254,"sat":144,"hue":13123, "transitiontime":0}' 2>/dev/null > /dev/null
curl -X PUT "http://192.168.0.66/api/$HUE/lights/2/state" -d '{"on":true, "bri":254,"sat":144,"hue":13123, "transitiontime":0}' 2>/dev/null > /dev/null
curl -X PUT "http://192.168.0.66/api/$HUE/lights/3/state" -d '{"on":true, "bri":254,"sat":144,"hue":13123, "transitiontime":0}' 2>/dev/null > /dev/null
curl -X PUT "http://192.168.0.66/api/$HUE/lights/5/state" -d '{"on":true, "bri":254,"sat":144,"hue":13123, "transitiontime":0}' 2>/dev/null > /dev/null
curl -X PUT "http://192.168.0.66/api/$HUE/lights/6/state" -d '{"on":true, "bri":254,"sat":144,"hue":13123, "transitiontime":0}' 2>/dev/null > /dev/null
