#!/usr/bin/env ruby
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |
#
# Office Lamp Arrangement 2018
# 4 - Office Spotlight
# 9 - Office Lightstrip
# 10 - Office Light Fixture (North Bulb)
# 11 - Office Light Fixture (South Bulb)
require 'trollop'

# Parse options
opts = Trollop.options do
  opt :off, "Off", type: :boolean, default: false
  opt :hue, "Hue", type: :integer, default: 46920
  opt :bri, "Brightness", type: :integer, default: 255
  opt :sat, "Saturation", type: :integer, default: 255
  opt :time, "Transition Time", type: :integer, default: 0
end
# lamp numbers
#lights=ARGV.empty? ? [1,2,3,5,6] : ARGV
lights=ARGV.empty? ? [4,9,10,11] : ARGV
opts[:on] = !opts[:off]

lights.each do |lamp|
  command = %Q[curl -X PUT "http://$HUE_IP/api/$HUE/lights/#{lamp}/state" -d '{"on":#{opts[:on].inspect}, "bri":#{opts[:bri]},"sat":#{opts[:sat]},"hue":#{opts[:hue]}, "transitiontime":#{opts[:time]}}' 2>/dev/null > /dev/null]
  puts command
  system command
end
