#!/bin/sh
# huewarm - a bright warm white, suitable for working but without the harsh blue
# glare of hueconcentrate. Brighter than huerelax, not as bright as hueday.
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |
#
# Office Lamp Arrangement 2018
# 4 - Office Spotlight
# 5 - Main Floor Office Lighstrip
# 9 - Upstairs Office Lightstrip
# 10 - Office Light Fixture (North Bulb)
# 11 - Office Light Fixture (South Bulb)

for lamp in 4 9 10 11; do
    curl -X PUT "http://$HUE_IP/api/$HUE/lights/$lamp/state" -d '{"on":true, "bri":254,"sat":50,"hue":13123, "transitiontime":30}' 2>/dev/null > /dev/null
done
