#!/bin/sh

usage_then_die() {
  echo "Usage:"
  echo "image_upload <image_file> [<remote_filename>]"
  exit 1
}

if [ $# -eq 0 ]; then
  usage_then_die
fi

if [ ! -e $1 ]; then
  echo "Could not find image file: $1"
  usage_then_die
fi

if [ -n "$2" ]; then
  DSTFILE=$2
else
  DSTFILE=`basename "$1"`
fi


echo scp "$1" "dikdik.shinybit.com:/var/www/html/images/$DSTFILE"
scp "$1" "dikdik.shinybit.com:/var/www/html/images/$DSTFILE"

echo ssh dikdik.shinybit.com chmod 664 "/var/www/html/images/$DSTFILE"
ssh dikdik.shinybit.com chmod 664 "/var/www/html/images/$DSTFILE"

echo "You can now access the image at: http://dikdik.shinybit.com/images/$DSTFILE"
