#!/bin/bash
# Because complying with an awful style guide is like winning Employee of the Month at Auschwitz in 1943
echo "jfmu (Just F[ix] Me Up right quick) is f(ixing) up your code right quick..."
echo "rubocop --auto-correct $*"
rubocop --auto-correct $*
