#!/usr/bin/env ruby
# 
# Create a new git repository on monkey, turn the current folder into
# a git repo, and push it to monkey.
# 
# Usage:
# 
# # creates repo in ./, commits it, creates copy on monkey, pushes it
# ~/foobar $ mknewrepo foobar.git
# 
# 
# # creates copy on monkey, pushes it
# ~/foobar $ mknewrepo --remote-only
# 
# TODO: Make interactive with -i. Detect each stage and prompt.

require 'trollop'

# opts = Trollop.options do
#   # TODO: This should autodetect!
#   opt :remote-only, "remote only; local repository is already created", :type => :boolean, :default => false
# end

repo = dir = ARGV[0] || File.basename(File.expand_path("."))

repo += ".git" unless repo =~ /\.git$/i

unless File.directory?(File.expand_path("./.git"))
  puts "Local repository does not exist; Creating local..."
  system "git init"
  system "git add ."
  system "git commit -m 'Initial commit'"
end

puts "Adding git@monkey.githero.com as remote..."
system "git remote add origin git@monkey.githero.com:#{repo}"

puts "Creating remote repository..."
system "ssh git@monkey.githero.com 'mkdir #{repo} && cd #{repo} && git --bare init'"

puts "Pushing local to origin..."
system "git push origin master"

puts "Tracking master..."
system "git track"
