#!/bin/sh
ifconfig | ruby -n -e '$line=$_.chomp; $iface=$1 if $line=~/^([\S]+):?/; puts "%8s: %s" % [$iface, $2] if $line =~ /(inet | inet addr:)(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/'
#echo External: `dig +short myip.opendns.com @resolver1.opendns.com`
echo External: `curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//'`
