#!/usr/bin/env ruby
# NO{{DEL}}COMMIT: You need to name this script
# {{SCRIPT}} - HEY DAVE COME DESCRIBE THIS SCRIPT
require "colorize"
require "optimist"
$:.unshift(File.expand_path("~/bin/lib"))
require "dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  def run
    @opts = Optimist.options do
      banner <<BANNER
# NO{{DEL}}COMMIT: You need to name this script
{{SCRIPT}} - HEY DAVE COME DESCRIBE THIS SCRIPT

Options:
BANNER
      opt :debug, "Print extra debug info", default: false
      opt :pretend, "Print commands but do not run them", default: false
      opt :verbose, "Run with verbose output (overrides --quiet)", default: false
      opt :quiet, "Run with minimal output", default: false
    end
    opts[:quiet] = !opts[:verbose] if opts[:verbose_given]
    puts opts.inspect if opts[:debug]

    # APP CODE GOES HERE
  end

end


if __FILE__ == $0
  Application.new.run
end
