#!/bin/bash
echo "It's the only way to be sure."

echo -e '\033[1;37;104m                                                                                 \033[0m'
echo -e '\033[1;37;104m  TODO: Make this check for the processes, tmux-send-keys to kill them itself,   \033[0m'
echo -e '\033[1;37;104m  then nuke the db, then restart the two services itself. I have the technology  \033[0m'
echo -e '\033[1;37;104m  just not the time to test it.                                                  \033[0m'
echo -e '\033[1;37;104m                                                                                 \033[0m'
echo -e '\033[1;37;41mStop your merchant portal server and merchant portal sidekiq (work:server and services:mpq).\033[0m'
echo -e 'Press ENTER to continue'
read

echo -e '\033[36mbin/rails db:drop db:create db:migrate\033[0m'
bin/rails db:drop db:create db:migrate

echo -e '\033[2;32m# seeder:required_data:run\033[0m'
echo -e '\033[1;33;40mGo start merchant_portal and I will reseed your data.\033[0m'
echo -e 'Press ENTER to continue'
read

echo -e '\033[2;32m# bin/rails seeder:sample_data:run\033[0m'
echo -e '\033[36mbin/rails runner "::Scripts::Db::Seeder.sample_data"\033[0m'
bin/rails runner "::Scripts::Db::Seeder.sample_data"

echo -e '\033[36mRAILS_ENV=test bin/rails db:drop db:create db:migrate\033[0m'
RAILS_ENV=test bin/rails db:drop db:create db:migrate
