#!/bin/sh
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |

curl -X PUT "http://192.168.0.66/api/$HUE/lights/1/state" -d '{"on":true, "bri":254,"sat":254,"hue":0, "transitiontime":0}'
curl -X PUT "http://192.168.0.66/api/$HUE/lights/2/state" -d '{"on":true, "bri":254,"sat":254,"hue":0, "transitiontime":0}'
curl -X PUT "http://192.168.0.66/api/$HUE/lights/3/state" -d '{"on":true, "bri":254,"sat":254,"hue":0, "transitiontime":0}'
