#!/usr/bin/env ruby

url = "https://docs.google.com/spreadsheets/d/#{ARGV.first}/edit#gid=0"

def osx?
  `uname -s`.strip == 'Darwin'
end

def dataservices_docker?
  ENV['IS_DOCKER_LOCAL'] == "1"
end

if osx?
  system "open #{url}"
elsif dataservices_docker?
  puts url
  puts "TODO: Figure out how to have docker tell host OS to open a url".yellow
else
  # In theory, sensible-browser is more correct than xdg-open, but in practice
  # it opens Mozilla Firefox even if chromium is my default browser
  system "xdg-open #{url} &> /dev/null"
end
