#!/bin/bash
echo -e "\033[36m(cd ~/data_services/etl/warehouse/finance && git apply ~/disable_retries_in_etl_nightly.patch)\033[0m"
(cd ~/data_services/etl/warehouse/finance && git apply ~/disable_retries_in_etl_nightly.patch)
