#!/bin/bash
# E501 is line-length, so
# autopep8 -d --exit-code --ignore E501 $* && echo "PEP8 OK" || echo '*** PEP8 VIOLATIONS DETECTED ***'
autopep8 -d --exit-code --ignore E501 $* && echo "PEP8 OK" || echo '*** PEP8 VIOLATIONS DETECTED ***'
