#!/usr/bin/env ruby
# pessimize-gem-version - transform gem name and version to pessimized gem spec
#
# Example: If you run
#     gem search -e faraday typhoeus ice_nine memorandum
# You get this output:
# *** REMOTE GEMS ***
#
# faraday (0.15.4)
#
# *** REMOTE GEMS ***
#
# typhoeus (1.3.1)
#
# *** REMOTE GEMS ***
#
# ice_nine (0.11.2)
#
# *** REMOTE GEMS ***
#
# memorandum (2.2.1)
#
# And if you pipe this into pessimize-gem-version, you should get this output:
# gem 'faraday', '~> 0.15.4'
# gem 'typhoeus', '~> 1.3'
# gem 'ice_nine', '~> 0.11.2'
# gem 'memorandum', '~> 2.2'
#
# Note that gems still on version 0 typically follow semantic versioning one
# step deeper, e.g. a minor version bump can introduce a breaking change while
# additive and documentation changes are relegated to micro version bumps.
ARGF.each_line do |line|
  line.strip!
  next unless line =~ /([^\s]+)\s\(([\d\.]+)\)/
  gem, version = $1, $2
  version = version.sub(/\.\d+$/, '') unless version.start_with?('0.')
  puts "gem '#{gem}', '~> #{version}'"
end
