#!/usr/bin/env ruby
# Consider putting 'os' in dotfiles/gems_i_always_want_in_global, and then
# require 'os'
# unless OS.osx? # etc
def osx?
  `uname -s`.strip == 'Darwin'
end

unless osx?
  puts "This script only runs on OSX, sorry. TODO: Find a linux equivalent of afplay"
  exit 1
end

ANNOYING = [1, 5]
SHORT = [2, 3, 4, 6]

intensity = if ARGV.empty?
              :random
            elsif ARGV[0] && (ARGV[0] == "--annoy" || ARGV[0] == "--annoying")
              :annoying
            elsif ARGV[0] && (ARGV[0] == "--god-damn" || ARGV[0] == "--holy-shit" || ARGV[0] =~ /^--f+u+(ck)?/i)
              :fuuuck
            end

case intensity
when :annoying
  mp3 = File.expand_path("~/bin/glassbreak%02d.mp3" % ANNOYING.sample)
  # puts mp3
  system "afplay #{mp3}"
when :fuuuck
  (SHORT.shuffle + [ANNOYING.sample]).each do |mp3|
    mp3 = File.expand_path("~/bin/glassbreak%02d.mp3" % mp3)
    # puts mp3
    system "afplay #{mp3} &"
    sleep(0.2)
  end
when :random
  mp3 = File.expand_path("~/bin/glassbreak%02d.mp3" % SHORT.sample)
  # puts mp3
  system "afplay #{mp3}"
end
