#!/usr/bin/env ruby
# pom - silly pom timer for shared tmate/ssh sessions
#
# Usage:
#
# pom # 25:00
# pom <seconds>
# pom mm:ss


# TODO: handle hours (WHY???)

# TODO: use ANSI.clear each frame so screen size doesn't matter

time = if ARGV[0]
         if ARGV[0] =~ /:/
           m,s = *ARGV[0].split(/:/).map(&:to_i)
           m * 60 + s
         else
           ARGV[0].to_i
         end
       else
         25 * 60
       end

ESC = 27.chr

# 20% of total time OR 1 minute, whichever is smaller
warning_time = [time * 0.2, 60].min

time.downto(0).each do |seconds|
  min = seconds / 60
  sec = seconds - (min*60)
  display = "%2d.%02d" % [min, sec]
  bg_color = if seconds <= warning_time
               "on_yellow"
             else
               "on_blue"
             end
#  print "#{ESC}[2J#{ESC}[0;0H"
#  puts output.inspect
  system "rubanner '#{display}' #{bg_color}"
  sleep 1
end
system 'rubanner "DONE" white on_green'
system 'say "Timer is done"'
