#!/usr/bin/env ruby
# pom - silly pom timer for shared tmate/ssh sessions
#
# Usage:
#
# pom # 25:00
# pom <seconds>
# pom mm:ss


# TODO: handle hours (WHY???)

# TODO: use ANSI.clear each frame so screen size doesn't matter

time = case ARGV[0]
       when /^\d*:\d\d:\d\d$/
         puts "H:MM:SS"
         h,m,s = *ARGV[0].split(/:/).map(&:to_i)
         h * 3600 + m * 60 + s
       when /^\d+:\d\d$/
         puts "MM:SS"
         m,s = *ARGV[0].split(/:/).map(&:to_i)
         m * 60 + s
       when /\d+/
         puts "SS"
         ARGV[0].to_i
       else
         puts "DEFAULT"
         25 * 60
       end

ESC = 27.chr

# 20% of total time OR 1 minute, whichever is smaller
warning_time = [time * 0.2, 60].min

time.downto(0).each do |seconds|
  hours = seconds / 3600
  min = seconds / 60 - (hours*60)
  sec = seconds - (min*60) - (hours*3600)
  display = if hours > 0
              "%d.%02d.%02d" % [hours, min, sec]
            else
              "%2d.%02d" % [min, sec]
            end
  bg_color = if seconds <= warning_time
               "on_yellow"
             else
               "on_blue"
             end
#  print "#{ESC}[2J#{ESC}[0;0H"
#  puts output.inspect
  system "rubanner '#{display}' #{bg_color}"
  sleep 1
end
system 'rubanner "DONE" white on_green'
# dbrady 2017-10-18: say is broken wtf/lol
# hangs with no sound in bash in Terminal
# works from bash in iTerm2
# hangs with no sound in ruby system() in Terminal AND iTerm
# "It Just Works" -- Some Guy Who Must Be Dead Now I Guess
#
# Update: Actually, it looks like it might be me trying to run two tmate
# sessions at once. In the second session, tssh and/or pbcopy do not work
# either.
#
# Steve Jobs is still dead though, so eh. Win some/Lose some
# system 'say "Timer is done"'
