#!/usr/bin/env ruby
#
# prittyxml - Receive a file or stream of XML and display it prittified

# So I wrot this big huge nasty string-scanning monster, but all I
# really need is this
#
# ...but this requires ActiveSupport v >3.0, so... ouch. Dunno. Gonna
# go ahead and use it since it gives me 99% of what I need for now.
require 'active_support/core_ext'
puts Hash.from_xml(ARGF.read).to_xml

