#!/bin/bash
# rc - "(rspec focus) clear" - clears rspec focus. See also rf, rg, and rh.
#
# usage:
#
# rc [-h]

if [ "$1" = "-h" ]; then
    rh
    exit 1
fi

echo 'Rspec Focus: Clear! (rf - Focus; rg - Go; rc - Clear; re - Edit; rv - View; rh - Help)'
echo "Clearing spec focus..."

rm -f ~/.spec_focus
