#!/bin/bash

log() {
    # Need -e to show colors in bash
    # must be omitted in sh (will print a literal "-e")
    echo -e "\033[32m$@\033[0m"
}

echo bundle exec yarn
bundle exec yarn

log bundle exec rails assets:clobber
bundle exec rails assets:clobber

log bundle exec rails assets:precompile
bundle exec rails assets:precompile

log bundle exec rails rswag:specs:swaggerize
bundle exec rails rswag:specs:swaggerize
