#!/usr/bin/env ruby
# refresh-and-rebuild-mp - refresh/update everything we can think of.
require "colorize"
require "optimist"
require_relative "bin/dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  def remaster?
    opts[:remaster]
  end

  def run
    @opts = Optimist.options do
      opt :debug, "Print extra debug info", default: false
      opt :pretend, "Print commands but do not run them", default: false
      opt :verbose, "Run with verbose output (overrides --quiet)", default: false
      opt :quiet, "Run with minimal output", default: false
      opt :remaster, "Remaster (pull and rebase from main branch) first", default: false
    end
    opts[:quiet] = !opts[:verbose] if opts[:verbose_given]
    puts opts.inspect if opts[:debug]

    commands = [
      "bundle",
      "npm install",
      "yarn install",
      "bin/rails assets:clobber",
      "bin/rails assets:precompile",
      "bin/rails rswag:specs:swaggerize",
      "git restore db/seeds.rb yarn.lock", # because these get outta sync alla time
    ]

    commands.unshift("remaster") if remaster?

    commands.each do |command|
      system %Q|rub1nner "#{command}"|
      puts command.cyan
      system command unless pretend?
    end
  end

end

if __FILE__ == $0
  Application.new.run
end
