#!/usr/bin/env ruby
# frozen_string_literal: true
# Run rails migrations on dev and test, but only if they're necessary
require "colorize"
require "optimist"
$:.unshift(File.expand_path("~/bin/lib"))
require "dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  opt_flag :force

  def run
    @opts = Optimist.options do
      banner <<BANNER
remigrate - migrate your local development and test databases.

This script:

1. uses are-rails-migrations-current to peek without starting Rails
2. If no migrations are needed, bails out quickly - no 10s Rails startup.
3. If any are needed, runs them in both development and test environments - no
   more forgetting to update your test environment.

Options:
BANNER
      opt :debug, "Print extra debug info", short: :d, default: false
      opt :force, "Force migrations to run anyway", short: :f, default: false
      opt :pretend, "Print commands but do not run them", short: :p, default: false
      opt :quiet, "Run with minimal output", short: :q, default: false
      opt :verbose, "Run with verbose output (overrides --quiet)", short: :v, default: false
    end
    opts[:quiet] = !opts[:verbose] if opts[:verbose_given]
    dump_opts if debug?

    run!
  end

  def run!
    if force? || !system("are-rails-migrations-current")
      # MP has custom migrations
      run_command "bin/rails db:reset" if merchant_portal?

      # run_command "diespringdie --db"
      run_command "bin/rails db:migrate", env: {"RAILS_ENV" => "development"}
      run_command "bin/rails db:migrate", env: {"RAILS_ENV" => "test"}
    else
      log "Your schema migrations appear to be up to date."
    end
  end

  # Merchant Portal has a really tricksome migration
  def merchant_portal?
    Dir.pwd =~ %r|acima/devel/.*merchant_portal.*|
  end

end


if __FILE__ == $0
  Application.new.run
end
