#!/bin/sh
# rfh - rspec focus help - show help message
echo -e 'Rspec Focus: Help! (rf - Focus; rg - Go; rc - Clear; rh - Help)'
echo -e "rfh - HELP   '(rspec focus) help' - show this help message"
echo -e "rff - \033[41;1mRECORD\033[0m '(rspec focus) focus <rspec params>' - focus specs by temporarily setting fixed args to rspec"
echo -e "rfg - \033[42;30;1mREPLAY\033[0m '(rspec focus) go' - runs focused specs by running with the fixed args"
echo -e "rfr - \033[44;1mRUN 1 \033[0m '(rspec focus) run' - runs only with the fixed args (ignores current focus entirely)"
echo -e "rfo - \033[44;1mRUNDOC\033[0m '(rspec focus) ordered run' - runs with --order=defined --format=documentation"
echo -e "rfe - \033[103;30mEDIT  \033[0m '(rspec focus) edit' - edit currently focused specs"
echo -e "rfv - \033[100mVIEW  \033[0m '(rspec focus) view' - view currently focused specs"
echo -e "rfc - CLR    '(rspec focus) clear' - clears currently focused specs"
echo -e "rfsave -     '(rspec focus) save <name>' - save currently focused spec to name"
echo -e "rfload -     '(rspec focus) load <name_or_blank_to_list>' - load a saved spec focus (leave name blank to list)"
echo
echo Current rspec focus is: `cat ~/.spec_focus`
exit 1
