#!/bin/bash
# rfr - "rspec run" run specs but wrapped with ci lights and timing
# basically it's a one-off rfg without reading or changing
# ~/.spec_focus and automatically add --format=documentation
# --order=defined
#
# usage:
#
# rfr [additional args or focus--will not change focus]

SING='n'

if [ "$1" = "-h" ]; then
    rfh
    exit 1
fi

if [ "$1" = "--sing" ]; then
    SING='y'
    shift
fi

echo 'Rspec Focus: RUN! (rff - Focus; rfg - Go; rfc - Clear; rfe - Edit; rfv - View; rfh - Help)'
echo "Running specs"
echo time bundle exec rspec  --format=documentation --order=defined $@
cirun
# TODO: Bring back the old, better version that parsed the RSpec output,
# e.g. if output includes /[1-9]+ failures/ cifail
# and if output include /[1-9]+ pending/ ciwarn
#
if [ "$SING" = 'y' ]; then
    echo 'SINGING SPECS ENABLED, YAY!!!'
    singbegin
    (time bundle exec rspec  --format=documentation --order=defined $@ && cipass && singpass || (cifail && singfail && exit -1))
else
    echo 'Non-singing specs (you can turn them on with --sing as the first argument)'
    (time bundle exec rspec  --format=documentation --order=defined $@ && cipass || (cifail && exit -1))
fi
