#!/bin/sh
# rh - rspec focus help - show help message
echo 'Rspec Focus: Help!'
echo "rf - '(rspec focus) focus' - focus specs by temporarily setting fixed args to rspec"
echo "rg - '(rspec focus) go' - runs focused specs by running with the fixed args"
echo "rc - '(rspec focus) clear' - clears focused specs"
echo "rh - '(rspec focus) help' - show this help message"
echo
echo Current rspec focus is: `cat ~/.spec_focus`
exit 1
