#!/bin/bash
# rsdiff - diff redshift/snowflake results
#
# tl;dr: `dscmp --log --csv --query="..."; rsdiff`
#
# Given dscmp log output to dscmp.redshift.csv and dscmp.snowflake.csv
# Blart them both to .json
# Calm down the snowflake all-caps column names
# Colordiff the the json

# ALTERNATE:
# if they're both one header line and one data line, we can transpose them and show them together
# (cat dscmp.redshift.csv && cat dscmp.snowflake.csv | ruby -ne 'puts $_ if $.>1')
#

source ~/bin/vars-ansicolors.sh


echo -e "\033[36mcsv-to-json dscmp.redshift.csv > dscmp.redshift.json\033[0m"
csv-to-json dscmp.redshift.csv > dscmp.redshift.json

echo -e "\033[36mcsv-to-json dscmp.snowflake.csv > dscmp.snowflake.json\033[0m"
csv-to-json dscmp.snowflake.csv | snow-calm-your-json > dscmp.snowflake.json

echo -e "\033[36mcolordiff -y dscmp.redshift.json dscmp.snowflake.json\033[0m"
colordiff -y dscmp.redshift.json dscmp.snowflake.json
