#!/usr/bin/env ruby
# rspec_hash_diff - display pretty, colorized side-by-side hash diff
# Usage:
# rspec_hash_diff [options] <diff_file>
#
# options:
# --no-sort:     do not sort hash keys before comparing, default is off (sorting
#                is on) TODO: THIS OPTION DOES NOT EXIST YET
#
# diff_file: Copy and paste JUST THE TWO LINES containing the red/green pair of
# expected/got hashes from an rspec failure. The first line will begin with
# a - and the second line will begin with a +. Save these two lines to a file
# and then run rspec_hash_diff <filename>.
#
# OSX only: Skip the filename saving part, just copy the 2 lines to the system
# clipboard and run this script with no args.
def osx?
  `uname -s`.strip == 'Darwin'
end

def usage
  puts <<USAGE
rspec_hash_diff [<diff_file>] - print a readable, colorized rspec hash diff

To use, copy the 2 lines containing JUST the rspec hash diff to a file and run
this script with that filename.
USAGE
  if osx?
    puts <<OSX_ONLY

OSX ONLY: This script will read directly from the clipboard if you omit the
filename. Just triple-click the first line, drag to select the second, and hit
Cmd-C. It needs to be in the *system* clipboard, not the tmux/tmate clipboard.
end
OSX_ONLY
  end
end

diff = if osx? && ARGV.empty?
         lines = `pbpaste`.each_line.to_a
         # test for >= 2 lines, if you copy a trailing line it's ok
         if lines.size < 2 || lines[0] !~ /^\s+-/ || lines[1] !~ /^\s+\+/
           usage
           exit -1
         end
         lines
       else
         IO.readlines ARGV.first
       end


txt1, txt2 = diff

txt1 = txt1.sub(/^\s*-/, '{').sub(/,\s*$/, '}')
txt2 = txt2.sub(/^\s*\+/, '{').sub(/,\s*$/, '}')

# I know, I know. eval() makes my skin crawl, too. Find me Hash.parse method
# that understands Hashes and Arrays as dumped by Hash#inspect and I'll switch
# these in a heartbeat. In the meantime, maybe don't put executable code in your
# hash diff file, mmmkay?
h1 = eval(txt1)
h2 = eval(txt2)
load File.expand_path(File.join(File.dirname(__FILE__),"hash_diff.rb"))
hash_diff h1, h2
