#!/usr/bin/env ruby
# rspec_hash_diff <diff_file>
# Usage: Copy and paste JUST THE TWO LINES containing the red/green pair of
# expected/got hashes from an rspec failure. The first line will begin with
# a - and the second line will begin with a +. Save these two lines to a file
# and then run rspec_hash_diff <filename>
diff_file = ARGV.first
txt1, txt2 = IO.readlines(diff_file)

txt1 = txt1.sub(/^\s*-/, '{').sub(/,\s*$/, '}')
txt2 = txt2.sub(/^\s*\+/, '{').sub(/,\s*$/, '}')

# I know, I know. It makes my skin crawl, too. Find me Hash.parse method that
# understands Hashes and Arrays as dumped by Hash#inspect and I'll switch these
# in a heartbeat. In the meantime, maybe don't put executable code in your hash
# diff file, mmmkay?
h1 = eval(txt1)
h2 = eval(txt2)
load File.expand_path(File.join(File.dirname(__FILE__),"hash_diff.rb"))
hash_diff h1, h2
