#!/usr/bin/env ruby
# rubanner - print a message with color
# rubanner [options] "message" [color [color2]]
#
# Example:
# rubanner "Cool Banner"
# rubanner "To Boldly Go" bold # black on white
# rubanner "This is bad" light_white on_red # light_white == bold
# rubanner "CoverMyMeds" --font=nancyj-improved bold red on_light_yellow # any colorize color string
#
# TODO:
# rubanner [options] "message" [options] --extra ["message2" [options]] [--extra [...]]
#
# e.g. our company logo could be approximated with:
# rubanner "Cover" on_light_white --font=nancyj-improved bold light_yellow \
#          --extra "My" bold light_red \
#          --extra "Meds" bold light_yellow

# Options:
# -f font_name, --font=font_name

# TODO: fiddle with colors inline. Would love to be able to say --left-background=light_yellow --right-background=light_red
# TODO: composed messages. Would LOVE to be able to say
#     rubanner Cover bold light_yellow on_light_white \
#              My bold light_red on_light_white \
#              Meds bold light_yellow on_light_white

require 'colorize'

argv = ARGV.dup
output = if idx = argv.index('-o')
           argv.delete_at idx
           File.open(argv.delete_at(idx), 'w')
         else
           $stdout
         end

require 'io/console'

screen_width = if idx = argv.index('-w')
                argv.delete_at(idx)
                argv.delete_at(idx).to_i
              else
                # Must supply -w to pipe to a file but if you DO
                # pipe $stdout.winzie will ASPLODE
                screen_width = $stdout.winsize[1]
              end

font = if idx = argv.index('-f')
         argv.delete_at idx
         argv.delete_at idx
       elsif idx = argv.index {|arg| arg =~ /^--font=/ }
         argv.delete_at(idx).split(/=/)[1]
       else
         'roman'
       end

message = argv.shift
colors = argv.empty? ? ['bold', 'on_blue'] : argv

if $DEBUG || ENV['RUBY_DEBUG']
  puts '-' * 80
  puts "Font: #{font}"
  puts "Message: #{message}"
  puts '--'
  argv.each.with_index do |arg, idx|
    puts "#{idx}: #{arg}"
  end
  puts '-' * 80
end

screen_width.inspect

banner = `figlet -w #{screen_width} -d ~/bin/figlet-fonts -f "#{font}" "#{message}"`
banner_width = banner.each_line.to_a.first.chomp.length
left_size = (screen_width - banner_width) / 2
right_size = screen_width - (banner_width + left_size)

lpad = ' ' * left_size
rpad = ' ' * right_size

def colorize(text, colors)
  colors.reduce(text) {|t, color| t.send color }
end


output.puts colorize("#{' ' * screen_width}", colors)

banner.each_line do |line|
  output.puts colorize("#{lpad}#{line.chomp}#{rpad}", colors)
end
# output.puts colorize("#{' ' * screen_width}", colors)
