#!/usr/bin/env ruby
# rupage - a fullscreen(ish) rubanner

require "optimist"
colors = [:black, :light_black, :red, :light_red, :green, :light_green, :yellow, :light_yellow, :blue, :light_blue, :magenta, :light_magenta, :cyan, :light_cyan, :white, :light_white]

opts = Optimist.options do
  opt :fg, "Foreground color", type: :string
  opt :bg, "Background color", type: :string
  opt :font, "Font", type: :string
  opt :bold, "Set bold text", default: false
end

puts opts.inspect

Optimist::die "Invalid fg #{opts[:fg].inspect} must be one of #{colors.join(', ')}" unless colors.include?(opts[:fg].to_sym)
Optimist::die "Invalid bg #{opts[:bg].inspect} must be one of #{colors.join(', ')}" unless colors.include?(opts[:bg].to_sym)

padding_command = "rubanner --fg=#{opts[:fg]} --bg=#{opts[:bg]} --font=#{opts[:font]} ' '"
banner_command = "rubanner --fg=#{opts[:fg]} --bg=#{opts[:bg]} --font=#{opts[:font]} \"#{ARGV * ' '}\""

system padding_command
system banner_command
system padding_command
