#!/usr/bin/env ruby
# rupage - a fullscreen(ish) rubanner

require "colorize"
require 'io/console'
require "optimist"

screen_y, screen_x = $stdout.winsize

colors = [:black, :light_black, :red, :light_red, :green, :light_green, :yellow, :light_yellow, :blue, :light_blue, :magenta, :light_magenta, :cyan, :light_cyan, :white, :light_white]

opts = Optimist.options do
  opt :fg, "Foreground color", default: "white"
  opt :bg, "Background color", default: "green"
  opt :font, "Font", default: "ansi-shadow"
  opt :bold, "Set bold text", default: true
  opt :debug, "Show extra debug info", default: false
end
message = ARGV.empty? ? " " : ARGV.join(" ")
puts opts.inspect if opts[:debug]

Optimist::die "Invalid fg #{opts[:fg].inspect} must be one of #{colors.join(', ')}" unless colors.include?(opts[:fg].to_sym)
Optimist::die "Invalid bg #{opts[:bg].inspect} must be one of #{colors.join(', ')}" unless colors.include?(opts[:bg].to_sym)

command_args = []
command_args << "--bg=#{opts[:bg]}" if opts[:bg]
command_args << "--bold" if opts[:bold]
command_args << "--font=#{opts[:font]}" if opts[:font]
command_args = command_args.join(" ")

padding_command = "rubanner #{command_args} ' '"
banner_command = "rubanner #{command_args} '#{message}'"
puts padding_command.cyan if screen_y > 20
puts banner_command.cyan

system padding_command if screen_y > 20
system banner_command
system padding_command  if screen_y > 20
