#!/usr/bin/env bash

if [ -e .rvmrc ]; then
    echo .rvmrc file exists -- cowardly refusing to overwrite.
    exit -1
fi

[ x$1 != x ] && GEMSET=@$1 || GEMSET=
[ x$2 != x ] && RUBY_VERSION=$2 || RUBY_VERSION=ruby-1.9

echo GEMSET: $GEMSET
echo RUBY_VERSION: $RUBY_VERSION

cat > .rvmrc <<EOF
#!/usr/bin/env bash

# This is an RVM Project .rvmrc file, used to automatically load the ruby
# development environment upon cd'ing into the directory

# First we specify our desired <ruby>[@<gemset>], the @gemset name is optional.
environment_id="$RUBY_VERSION$GEMSET"

#
# First we attempt to load the desired environment directly from the environment
# file, this is very fast and efficicent compared to running through the entire
# CLI and selector. If you want feedback on which environment was used then
# insert the word 'use' after --create as this triggers verbose mode.
#
if [[ -d "${rvm_path:-$HOME/.rvm}/environments" \
  && -s "${rvm_path:-$HOME/.rvm}/environments/$environment_id" ]] ; then
  \. "${rvm_path:-$HOME/.rvm}/environments/$environment_id"
else
  # If the environment file has not yet been created, use the RVM CLI to select.
  rvm --create  "$environment_id"
fi

EOF

