#!/bin/bash
# 
# Search a database schema for a column.
# 
# schemagrep <database> <table> [grep_options] <grep_term> - grep in a schema
# NOTE: bash doesn't quite let me slice and dice args as cleanly as I might have liked, so this script is limited to 8 arguments.
# 
# TODO: It may actually be limited to 1 argument. More than 1 search term seems buggy.

function scantable {
	if (mysql -D $1 -e "DESCRIBE $2" | grep -q $3 $4 $5 $6 $7 $8 $9); then
		echo "--- $2 ---"
		mysql -D $1 -e "DESCRIBE $2" | grep $3 $4 $5 $6 $7 $8 $9
		echo ""
	fi
}

for table in $(for row in $(mysql -D $1 --skip-column-names --raw -e 'show tables'); do echo $row; done); do scantable $1 $table $2 $3 $4 $5 $6 $7 $8; done
