#!/bin/bash
# set-ds-script <script> - Record scriptfile
SCRIPTFILE=~/.ds_script

if [ `uname -s` == 'Darwin' ]; then
    echo -e "\033[33mYou are in OSX. DS script only makes sense from inside Docker. Aborting.\033[0m"
    exit -1
fi

# If ds table is cached, clear it
clear-ds-table

echo "# The last line of this file contains the current working ds script." | tee $SCRIPTFILE
echo "# it is a relative path from the ds/etl/warehouse folder" | tee -a $SCRIPTFILE
echo "# see ~/bin/get-ds-script, ~/bin/set-ds-script, and ~/bin/clear-ds-script" | tee -a $SCRIPTFILE
echo "$@" | tee -a $SCRIPTFILE
