#!/bin/bash
# set-ds-script <script> - Record scriptfile
SCRIPTFILE=~/.ds_script

echo "# The last line of this file contains the current working ds script." | tee $SCRIPTFILE
echo "# it is a relative path from the ds/etl/warehouse folder" | tee -a $SCRIPTFILE
echo "# see ~/bin/get-ds-script, ~/bin/set-ds-script, and ~/bin/clear-ds-script" | tee -a $SCRIPTFILE
echo "$@" | tee -a $SCRIPTFILE
