#!/usr/bin/env ruby
# sha - dump a SHA hash of given text/files.
# 
# Usage:
#   sha <file> [<file>]
#   echo "foo" | sha
# 
# NOTE: Not terribly memory efficient. Holds all text in memory before
# creating the digest.

require 'digest/md5'

content = ''
ARGF.each do |file_contents|
  file_contents.each_line do |line|
    content += line
  end
end

puts "#{Digest::SHA1.hexdigest(content)}"
