#!/usr/bin/env ruby

require "json"

json = JSON.parse(File.read("remaining-work.json"))

json.each do |item|
  link = "https://acima.atlassian.net/browse/DS-#{item['id']}"
  file = item['comment'].split(/\|/).first

  puts "#{link} - #{file}"
end
