#!/usr/bin/env ruby
# skip-ticket <id> [reason] - Add a new ticket to skip in jira.py
require 'json'

id, *comment = ARGV

id = id.to_i
comment = comment * ' '

puts "id:      #{id}"
puts "comment: #{comment}"

FILENAME = File.expand_path("~/jira-bad-tickets.json")

tickets = JSON.parse(File.read(FILENAME))

new_ticket = { "id": id, "comment": comment }

puts tickets

# if ticket already exists, update the comment.
if tickets["tickets"].map {|ticket| ticket["id"] }.include?(id)
  index = tickets["tickets"].index {|ticket| ticket["id"] == id }
  tickets["tickets"][index] = new_ticket
else
  tickets << new_ticket
end

File.open(FILENAME, "w") do |file|
  file.puts JSON.pretty_generate(tickets)
end
