#!/bin/bash
# slack_adhd_strobe_nightmare - historically relevant artifact from CMM. Ask me
# about the story behind this sometime. (I probably won't tell you, but you can
# ask.) tl;DR when the unicorn was slain and its blood was drunk by the acolytes
# of the beast, the startup went from paradaise to hellscape without ever
# passing through "tolerable", but it did spend a lot of time masquerading as
# "mostly worth it". Pip pip, old chum! Sigh.
if [ `uname -s` != "Darwin" ]; then
    echo "Sorry, this script only runs on OSX."
    exit -1
fi

while true; do
    echo 'sleep 600; say "Check Slack"; seq 10 | while read i; do rubanner -B -g yellow -b black "CHECK SLACK" && rubanner -B -b yellow "CHECK SLACK"; done; say "Check Slack"'
    sleep 600
    say "Check Slack"
    seq 10 | while read i; do
        rubanner -B -b on_yellow "CHECK SLACK"
        rubanner -B -b on_black -g yellow "CHECK SLACK"
    done
    say "Check Slack"
done
