#!/usr/bin/env ruby
# snow-create-pr-finance - emit the url for creating a PR against the snowflake branch in the finance repo


# TODO: look into adapting git-home to get the pull request url?
home = "https://github.com/acima-credit/data_services_finance"

branch = `git current-branch`.strip
pr_name = branch.sub(%r|^feature/|, '')
ticket_id = $1 if branch =~ /(\d+)/

puts "\033[93mYou can run this script from inside Docker if it's more convenient. It emits the link but does not try to open a browser.\033[0m" unless ENV["IS_DOCKER_LOCAL"]

puts "\033[36m#{home}/compare/feature/snowflake-moveover...#{branch}?expand=1&title=#{pr_name}\033[0m"
puts pr_name
puts "Jira Ticket: https://acima.atlassian.net/browse/DS-#{ticket_id}"
