#!/bin/bash

echo "This will attempt to fix all the things. Make sure the script you really want to fix up is this file:"
[ "$1" == "" ] && echo `get-ds-script` || echo $1

# 2023-06-28 - temp disable for BI sql/folder
echo -e "\033[37;41mSkipping git-isclean (disabled 2023-06-28 for sql/ refactoring)\033[0m"

# git-isclean &&
#     echo "(It looks clean from here.)" || (echo -e "\033[1;37;41mBranch is not clean\033[0m" && exit)
# echo "Hit CTRL-C to abort. Otherwise, hit ENTER to begin."
# read

# now run all the snow-fix-* scripts
# snow-fix-tabs $1
# snow-fix-whitespace $1
# snow-fix-pep $1
snow-fix-btrim $1
snow-fix-distkeys $1
# snow-fix-chdir $1
# snow-fix-optional-job-config $1
# snow-fix-except-exception $1
snow-fix-varchar-sizing $1

# This is a partial fix only, and does not commit the fix. Run it manually.
# snow-fix-timezones
