#!/bin/bash
# snow-fix-whitespace
# not sure why sed -E -i 's/\s+$//' doesn't work

SCRIPT=`get-ds-script`

if [ -z "$SCRIPT" ]; then
    echo "You must set the SCRIPT variable first."
    exit -1
fi

echo -e "\033[36msed -i -E 's/BTRIM\(/TRIM\(/ig' $SCRIPT\033[0m"
sed -i -E 's/BTRIM\(/TRIM\(/ig' $SCRIPT

snow-commit-ds-script "Change BTRIM to TRIM"
