#!/usr/bin/env ruby
# post export SCRIPT=<script>, then git new-branch in both repos
# snow-new-branch <ticket> <file> - git new-branch in both repos
require "colorize"

def usage
  puts <<USAGE
snow-new-branch <ticket> <file> - create new snowflake branches in both repos
USAGE
end

if ARGV.include?("-h") || ARGV.include?("--help")
  usage
  exit 0
end

if ARGV.first.to_i.zero?
  puts "First argument must be a ticket id"
  usage
  exit -1
end

if ARGV.size != 2
  puts "Expected 2 arguments, got #{ARGV.size}"
  usage
  exit -1
end

ticket, filename = *ARGV
warehouse_dir = File.expand_path("~/data_services/etl/warehouse")

if Dir.pwd != warehouse_dir
  puts "ERROR: Must be run from the warehouse dir."
  puts "warehouse_dir: #{warehouse_dir.inspect}"
  puts "      Dir.pwd: #{Dir.pwd.inspect}"
  exit -1
end

if !File.exists?(filename)
  puts "ERROR: file '#{filename}' does not exist"
  exit -1
end

job_name = filename.sub(%r|/|, '.').sub(/\.py$/, '')

puts "export SCRIPT=#{filename}"

command = "git new-branch #{ticket} #{job_name}"

system command
Dir.chdir("finance") do
  system command
end
