#!/bin/bash
if [ -z "$SCRIPT" ]; then
    echo "You must set the SCRIPT variable first."
    exit -1
fi

echo git add $SCRIPT
git add $SCRIPT

echo git commit -m "Update $SCRIPT to be compatible with Snowflake"
git commit -m "Update $SCRIPT to be compatible with Snowflake"
