#!/usr/bin/env ruby
# snow-make-links-for-zack - generate all the PR links for a job's migrations
#
# IMPORTANT TODO: WRITE DOWN ALL THE LINKS WE MAKE. If Zack gets way behind and
# then has multiple feedback issues, I need to be able to find my open PRs and
# tickets. This needs to be omnidirectional, if I forget to put the jira ticket on
# the github PR or Jira can't find the PRs, I am likely to have one number and
# not the others.
#
# So if I'm on ticket 1533 and say snow link 2723 428, I need to be able to take
# any of those numbers and find the others.
#
# Look at git-set-pr and git-get-pr, I think I had part of the idea going
# there. If I run get-set-pr with no arguments it should get the ticket from the
# branch and the repo from the cwd.

def usage
  str = <<USAGE
#{File.basename(__FILE__)} <WAREHOUSE_PR_ID> <FINANCE_PR_ID> [<PACKAGE_PR_ID>]
USAGE
end

if ARGV.size < 2 || ARGV.size > 3 || ARGV.include?('-h') || ARGV.include?('--help')
  puts usage
  exit -1
end


def get_ticket_from_branch
  `git current-branch`.gsub(/^\D*/, '').to_i
end

TICKET_ID=get_ticket_from_branch
WAREHOUSE_PR_ID=ARGV[0]
FINANCE_PR_ID=ARGV[1]
PACKAGE_PR_ID=ARGV[2]

proposed_branch_name = `git current-branch`.strip.sub(%r|^feature/|,'')
job_name = proposed_branch_name.sub(%r|^\w+-\d+/|, '')

blurb =<<TEMPLATE
*DS-#{TICKET_ID}: #{job_name}*
Jira Ticket: https://acima.atlassian.net/browse/DS-#{TICKET_ID}
Dataservices PR: https://github.com/acima-credit/data_services/pull/#{WAREHOUSE_PR_ID}
Finance PR: https://github.com/acima-credit/data_services_finance/pull/#{FINANCE_PR_ID}
TEMPLATE

if PACKAGE_PR_ID
  blurb += "Package PR: https://github.com/acima-credit/data_services_package/pull/#{PACKAGE_PR_ID}\n"
end

puts "Branch Name: #{proposed_branch_name}"
puts
puts blurb
puts
puts "1. Copy this to the clipboard"
puts "2. Update JIRA ticket with PR info"
puts "3. Update PRs with JIRA tickets"
puts "4. Paste this blurb to Zack (CMD-v CMD-SHIFT-f)"
