#!/bin/bash
SCRIPT=`get-ds-script`

if [ -z "$SCRIPT" ]; then
    echo "You must set the SCRIPT variable first."
    exit -1
fi

echo -e "\033[36mpep-fix $SCRIPT\033[0m"
pep-fix $SCRIPT

snow-commit-warehouse-pep8-conformance
