#!/bin/bash
# snow-fix-chdir

SCRIPT=`get-ds-script`

if [ -z "$SCRIPT" ]; then
    echo "You must set the SCRIPT variable first."
    exit -1
fi

echo -e "\033[36msed -E -i '/\bos.chdir\b/d' $SCRIPT\033[0m"
sed -E -i '/\bos.chdir\b/d' $SCRIPT

snow-commit-warehouse-chdir
