#!/bin/bash
# snow-go-main

# if [ `uname -s` == "Darwin" ]; then
#     echo -e "\033[31mThis script runs in Docker, not OSX.\033[0m"
#     exit -1
# fi

echo -e "WARNING! This will reset your warehouse and finance repos to the \033[1;37;104m❄️ ❄️ ❄️  SNOWFLAKE ❄️ ❄️ ❄️ \033[0m main branch, feature/snowflake-moveover."
if [[ $1 == "-c" || $1 == "--clear" ]]; then
    echo "It will also clear the ~/.ds_script and ~/.ds_table files."
else
    echo "Call this script with -c or --clear to also clear the ~/.ds_script and ~/.ds_table files."
fi
echo HIT CTRL-C TO ABORT, PRESS ENTER OTHERWISE:
read

echo starting... &&

    # Move warehouse back to feature/snowflake-moveover
    echo -e "\033[94mcd ~/data_services/etl/warehouse/\033[0m" &&
    (cd ~/data_services/etl/warehouse/ &&

         # echo -e "\033[36mgit reset --hard\033[0m" &&
         # git reset --hard &&

         echo -e "\033[36mgit co feature/snowflake-moveover\033[0m" &&
         git co feature/snowflake-moveover &&

         echo -e "\033[36mgit pull\033[0m" &&
         git pull) &&

    # Move finance submodule back to feature/snowflake-moveover
    echo -e "\033[94mcd ~/data_services/etl/warehouse/finance\033[0m" &&
    (cd ~/data_services/etl/warehouse/finance &&

         echo -e "\033[36mgit reset --hard\033[0m" &&
         git reset --hard &&

         echo -e "\033[36mgit co feature/snowflake-moveover\033[0m" &&
         git co feature/snowflake-moveover &&

         echo -e "\033[36mgit pull\033[0m" &&
         git pull) &&

    (
        (test "$1" == "-c" || test "$1" == "--clear") &&
            echo -e "\033[36mclear-ds-script\033[0m" &&
            echo clearing ~/.ds_script or ~/.ds_table &&
            clear-ds-script
    ) || (
        echo NOT clearing ~/.ds_script or ~/.ds_table
    ) &&
        echo done.
