#!/bin/bash
SCRIPT=`get-ds-script`

if [ -z "$SCRIPT" ]; then
    echo "You must set the SCRIPT variable first."
    exit -1
fi

JOB=`echo $SCRIPT | sed -e 's/\//./g' | sed -E 's/.py$//'`

echo git add config/etl_nightly_config.json
git add config/etl_nightly_config.json

echo "git commit -m \"Configure $JOB to run on Snowflake\""
git commit -m "Configure $JOB to run on Snowflake"
