#!/usr/bin/env ruby
# snow-make-links-for-zack - generate all the PR links for a job's migrations

def usage
  str = <<USAGE
#{File.basename(__FILE__)} <WAREHOUSE_PR_ID> <FINANCE_PR_ID> [<PACKAGE_PR_ID>]
USAGE
end

if ARGV.size < 2 || ARGV.size > 3 || ARGV.include?('-h') || ARGV.include?('--help')
  puts usage
  exit -1
end


def get_ticket_from_branch
  `git current-branch`.gsub(/^\D*/, '').to_i
end

TICKET_ID=get_ticket_from_branch
WAREHOUSE_PR_ID=ARGV[0]
FINANCE_PR_ID=ARGV[1]
PACKAGE_PR_ID=ARGV[2]

proposed_branch_name = `git current-branch`.strip.sub(%r|^feature/|,'')
job_name = proposed_branch_name.sub(%r|^\w+-\d+/|, '')

blurb =<<TEMPLATE
*DS-#{TICKET_ID}: #{job_name}*
Jira Ticket: https://acima.atlassian.net/browse/DS-#{TICKET_ID}
Dataservices PR: https://github.com/acima-credit/data_services/pull/#{WAREHOUSE_PR_ID}
Finance PR: https://github.com/acima-credit/data_services_finance/pull/#{FINANCE_PR_ID}
TEMPLATE

if PACKAGE_PR_ID
  blurb += "Package PR: https://github.com/acima-credit/data_services_package/pull/#{PACKAGE_PR_ID}\n"
end

puts "Branch Name: #{proposed_branch_name}"
puts
puts blurb
puts
puts "1. Copy this to the clipboard"
puts "2. Update JIRA ticket with PR info"
puts "3. Update PRs with JIRA tickets"
puts "4. Paste this blurb to Zack (CMD-v CMD-SHIFT-f)"
