#!/bin/bash

echo "This will attempt to fix all the things. Make sure the script you really want to fix up is this file:"
echo `get-ds-script`

git-isclean &&
    echo "(It looks clean from here.)" || (echo -e "\033[1;37;41mBranch is not clean\033[0m" && exit)

echo "Hit CTRL-C to abort. Otherwise, hit ENTER to begin."
read

# now run all the snow-fix-* scripts
snow-fix-tabs
snow-fix-whitespace
snow-fix-pep
snow-fix-distkeys
snow-fix-chdir
snow-fix-optional-job-config
snow-fix-except-exception
snow-fix-varchar-sizing

# This is a partial fix only, and does not commit the fix. Run it manually.
# snow-fix-timezones
