#!/bin/bash
echo 'WARNING! This will commit your warehouse and finance branches, push them up, and give you create-pr links'
echo HIT CTRL-C TO ABORT, PRESS ENTER OTHERWISE:
read

echo -e "\033[36mgit cram && (cd finance && snow-commit-finance-config && git cram && snow-create-pr-finance) && snow-create-pr-warehouse\033[0m"
git cram && (cd finance && snow-commit-finance-config && git cram && snow-create-pr-finance) && snow-create-pr-warehouse
