#!/bin/bash
# snow-fix-whitespace
# trim space at EOL and ensure exactly 1 newline at EOF
SCRIPT=`get-ds-script`

if [ -e "$1" ]; then
    SCRIPT=$1
    shift
fi

if [ -z "$SCRIPT" ]; then
    echo "You must set the SCRIPT variable first."
    exit -1
fi

system "cleanup-whitespace"

snow-commit-ds-script "Clean up whitespace"
