#!/usr/bin/env ruby
# snow-job-show-config - Dump the config for a job (defaults to $SCRIPT)
require 'json'

script = (ARGV.first || ENV["SCRIPT"]).sub(%r|/|, '.').sub(/\.py$/, '')

config = File.read(File.expand_path("~/data_services/etl/warehouse/finance/config/etl_nightly_config.json"))

json = JSON.parse(config)

body = json["jobs"][script]

block = { script => body }

# colorize redshift red on black, colorize snowflake icy white on light blue
puts JSON.pretty_generate(block).gsub("redshift", "\033[31mredshift\033[0m").gsub("snowflake", "\033[97;104msnowflake\033[0m")
