#!/usr/bin/env ruby
# snow-commit-ds-script "<commit_message>" - add and commit current ds script with message
# appends "in  $SCRIPT" if it isn't already there
script=`get-ds-script`.strip
commit_message=ARGV * ' '

if script.empty?
    puts "You must set the SCRIPT variable first."
    exit -1
end

commit_message += " in #{script}" unless commit_message&.end_with?("in #{script}")

def command(cmd)
  puts "\033[36m#{cmd}\033[0m"
  system cmd
end

command "git add #{script}"
command "snow-script-has-changes && git commit -m \"#{commit_message}\" || echo '\033[32mNo changes made to script; not committing.\033[0m'"
