#!/bin/sh
# | color   |   hue |
# |---------+-------|
# | red     |     0 |
# | yellow  | 12750 |
# | green   | 25500 |
# | blue    | 46920 |
# | magenta | 56100 |

curl -X PUT "http://192.168.0.66/api/$HUE/lights/6/state" -d '{"on":false}' 2>/dev/null > /dev/null
