#!/bin/sh
# ssh-pushkey: Add an sshkey to a remote server. Ensures .ssh/ and
# .ssh/authorized_keys exist and are chmod 700 and 600 respectively.
# 
# Usage: ssh-pushkey host key
HOST=$1
KEYSRC=$2
KEY=$(basename $2)

# TODO: When I grow up, I really want to be a Capistrano task. That's why this file isn't very well documented.

echo "Ensuring .ssh folder exists..."
echo "ssh $HOST 'mkdir -p .ssh && chmod 700 .ssh'"
ssh $HOST 'mkdir -p .ssh && chmod 700 .ssh'

echo "Copying keys..."
echo "scp $KEY $HOST:.ssh/..."
scp $KEYSRC $HOST:.ssh/

echo "Catting key into authorized_keys..."
echo "ssh $HOST \"cat .ssh/$KEY >> .ssh/authorized_keys\" && chmod 600 .ssh/authorized_keys"
ssh $HOST "cat .ssh/$KEY >> .ssh/authorized_keys && chmod 600 .ssh/authorized_keys"

