#!/usr/bin/env ruby

# sshforget - forget a known ssh host.
#
# If you get this error message:
# 
# ----------
# Add correct host key in /Users/dbrady/.ssh/known_hosts to get rid of this message.
# Offending key in /Users/dbrady/.ssh/known_hosts:29
# RSA host key for fe1.lmpcloud.com has changed and you have requested strict checking.
# Host key verification failed.
# ----------
# 
# You can do either of the following:
# 
# sshforget 29
# sshforget fe1.lmpcloud.com
# 
# And the offending line will be removed.

@match_by_line = true unless ARGV[0].to_i.zero?
if @match_by_line
  @line_number = ARGV[0].to_i 
else
  @pattern = /^#{ARGV[0]}/
end

if @match_by_line
  puts "Removing line #{ARGV[0]} from known_hosts..."
else
  puts "Removing host #{ARGV[0]} from known_hosts..."
end

@matches_found = 0

new_file = []
IO.readlines(File.expand_path("~/.ssh/known_hosts")).each_with_index do |line, i|
  i = i+1
  if (@match_by_line && i==@line_number) || (!@match_by_line && line =~ @pattern)
    @matches_found += 1
    puts "Removing host key: #{line}"
  else 
    new_file << line
  end
end


File.open(File.expand_path("~/.ssh/known_hosts"), "w") do |file|
  file.puts new_file
end

puts "All done. #{@matches_found} matches were found and removed."
