#!/usr/bin/env ruby
# Stupid script to quickly find and bring up the practice tabs for
# Stairway to Heaven on Ukulele. Just because I publish my bin files doesn't
# mean they're for anybody but me. ;-) BUUUUT if you care, to make this work
# you'll also need my refdox repo. Clone it in your Documents folder.
filename = File.expand_path("~/Documents/refdox/stairway.txt")
line_number = 0

puts
IO.readlines(filename).each do |line|
  line_number += 1
  next unless (31..64).cover? line_number
  puts line.rstrip
end
puts
