#!/bin/bash
if [ `uname -s` == 'Darwin' ]; then
    echo launchctl unload /Library/LaunchAgents/com.symless.synergy.synergy-service.plist
    launchctl unload /Library/LaunchAgents/com.symless.synergy.synergy-service.plist
else
    echo sudo service synergy stop
    sudo service synergy stop
fi
