#!/bin/bash
if [ `uname -s` == 'Darwin' ]; then
    echo launchctl load /Library/LaunchAgents/com.symless.synergy.synergy-service.plist
    launchctl load /Library/LaunchAgents/com.symless.synergy.synergy-service.plist
else
    echo sudo service synergy start
    sudo service synergy start
fi
