#!/usr/bin/env ruby
# 
# tablecounts.rb - List the tables from a database and the number of
# records in each table. Moderately useful when trying to size up a
# new database.
require 'rubygems'
require 'mysql'
require 'ruport'

database=ARGV[0] || 'leadgen_development'

def max(a,b)
  a>b ? a : b
end

begin
  # connect to the MySQL server
  dbh = Mysql.real_connect("localhost", "root", "", database)
  report = Ruport::Data::Table(%w[table rows])
  
  # get tables
  tables = []
  rows = []
  res = dbh.query("SHOW TABLES")
  while row = res.fetch_row do
    tables << row[0]
  end
  res.free
  $stderr.puts "#{database} has #{tables.size} tables. Querying table sizes..."
  $stderr.puts "[" + ("_" * tables.size) + "]"

  $stderr.print "["
  columns = 0
  tables.each do |table|
    res2 = dbh.query("SELECT COUNT(*)  FROM #{table}")
    while row2 = res2.fetch_row do
      report << { "table" => table, "rows" => row2[0] }
    end
    res2.free
    $stderr.print "^"
    $stderr.flush
  end
  $stderr.puts "]"

  puts report
rescue Mysql::Error => e
  puts "Error code: #{e.errno}"
  puts "Error message: #{e.error}"
  puts "Error SQLSTATE: #{e.sqlstate}" if e.respond_to?("sqlstate")
ensure
  # disconnect from server
  dbh.close if dbh
end

