#!/usr/bin/env ruby
# test-migration - test a migration to see that it's working correctly

# TODO: Test that migration works/does not crash if the table is
# missing. (I.e. ALTER TABLE to rename it to something else.)
#
# ALTER TABLE <table> RENAME TO <table>_backup_<datestamp>
#
# ...don't forget to rename it back later, especially for violently important
# tables like leases or merchants.

# Assuming the migration is to add a column to a table
# test-migration <table> <column>

# TODO: Look at are-rails-migrations-current for database stuff without waiting on rails?

# Before migration
# Test: Table must not have column

# Test: Run migration, it must not crash

# After migration
# Test: table must have column

# Idempotency: connect to database and secretly remove the migration from schema_migrations

# Test: Run migration, it must not crash
# Test: table must have column

# Rollback

# Test: table must not have column

# Remigrate

# Test: Run migration, it must not crash
# Test: table must have column

# BONUS FEATURE: Emit github-friendly checklist:
# - [x] Premigration column does not exist
# - [x] Migration adds column
# - [x] Migration is idempotent
# - [x] Rollback removes column
# - [x] Remigration succeeds
