#!/bin/bash
# Rewrite the command line when screenshotting the command is more valuable than
# seeing the script name in the history
echo -ne "\033[1F# "

echo 'cd ~/data_services_package/ && time python -m unittest tests.db_connectors.snowflake.test_build_unload_sql.TestBuildUnloadSql' $@
cd ~/data_services_package/ && time python -m unittest tests.db_connectors.snowflake.test_build_unload_sql.TestBuildUnloadSql $@
