#!/usr/bin/env ruby
# tidy-xml - Parse incoming xml (from file or $stdin) and spit it back out with
# best-effort indentation
require "optimist"
require "nokogiri"

opts = Optimist.options do
  opt :indent, "number of spaces to indent", default: 2
end

doc = Nokogiri::XML(ARGF)
puts doc.to_xml(indent: opts[:indent])
