#!/bin/bash
ps auwx | grep [t]mux && echo "Tmux is already running, sorry--shutting down." && exit 1
ps auwx | grep [t]mate && echo "Tmate is already running, sorry--shutting down." && exit 1
TCMD=tmate tshare-start $*
