#!/usr/bin/env ruby

# a general idea putting place

# not putting in new-ruby yet, this is just a wishlist/RDD/ToDD

# toto - cli/share of TODO.org

# emoji ? emojidb helper

# voxjrn - slurp audio off recorder, transcribe with AI, revise interactively with AI?

# >>> interactive assisted revision, like code but for other genres: valuable?
