#!/bin/bash
target=queues
count=7

for i in $(seq $count); do
    echo $i
    echo "tmux send-keys -t${target}:$i C-c"
    tmux send-keys -t${target}:$i "C-c"
    tmux send-keys -t${target}:$i "C-d"
done
