#!/bin/bash

# triad2 <root> <3rd> <5th>

# This is just an attempt to make this monster easier to type:
# fretmap -t G,D,B | sed -E "s/ G /\x1b[30;102m G \x1b[0m/g" | sed -E "s/ D /\x1b[30;106m D \x1b[0m/g" | sed -E "s/ B /\x1b[30;106m B \x1b[0m/g"

ROOT="\x1b[30;102m"
THIRD="\x1b[97;44m"
FIFTH="\x1b[97;44m"
fretmap -t $1,$2,$3 | sed -E "s/\| $1(\s*)/|$ROOT $1\1\x1b[0m/g" | sed -E "s/\| $2(\s*)/|$THIRD $2\1\x1b[0m/g" | sed -E "s/\| $3(\s*)/|$FIFTH $3\1\x1b[0m/g"
