#!/bin/bash
# New feature: I *DO* want to be able to run 3-4 separate tmux sessions at
# once. Ouch/cool.
#
# grep note: `ps auwx | grep tmux` will find tmux AND the "grep tmux" process;
# `ps auwx | grep [t]mux` will only find the actual tmux process. A clever bash
# hack is to put square brackets around the first letter. This parses out as
# "grep tmux" but the grep process lists in ps as "grep [t]mux" which does NOT
# match the "tmux" regex.
#
# ps auwx | grep [t]mux && echo "Tmux is already running, sorry--shutting down." && exit 1
# ps auwx | grep [t]mate && echo "Tmate is already running, sorry--shutting down." && exit 1

TCMD=tmux tshare-start services
