#!/usr/bin/env ruby
# frozen_string_literal: true
# tsend - send keys to tmux session(s)
require "colorize"
require "optimist"
$:.unshift(File.expand_path("~/bin/lib"))
require "dbrady_cli"
String.disable_colorization unless $stdout.tty?

class Application
  include DbradyCli

  opt_flag :suppress_newline

  def run
    @opts = Optimist.options do
      banner <<BANNER
tsend - send keys to tmux session

tsend                        - list sessions and their windows, you're welcome
tsend work 1 "emacs" C-m     - open emacs in window 1 of the work session
TODO: tsend work "ls" C-m          - send ls command to the current window of the work session
TODO: tsend work --all C-c

# tsend - send keys to tmux session(s)

Options:
BANNER
      opt :debug, "Print extra debug info", short: :d, default: false
      opt :suppress_newline, "Suppress newline/enter after sending", short: :n, default: false
      opt :pretend, "Print commands but do not run them", short: :p, default: false
      opt :quiet, "Run with minimal output", short: :q, default: false
      opt :verbose, "Run with verbose output (overrides --quiet)", short: :v, default: false
    end
    opts[:quiet] = !opts[:verbose] if opts[:verbose_given]
    dump_opts if debug?

    run!
  end

  def run!
    if ARGV.empty? || ARGV.first.to_s.downcase == "list"
      list_sessions
    elsif ARGV.size < 3
      puts "Expected 3 arguments, got #{ARGV.size}. Currently you must specify session, window, and message"
      exit 1
    else
      argv = ARGV.dup
      session = argv.shift
      window = argv.shift.to_i
      message = argv.join(' ').inspect
      # TODO: ensure session and window exist
      message += " C-m" unless suppress_newline?

      command = "tmux send-keys -t #{session}:#{window} #{message}"
      puts command.magenta
      run_command command
    end
  end

  def list_sessions
    get_command_output_lines("tmux list-sessions")
      .map { |session| session.sub(/(\d+) windows.*$/, "\\1 windows") }
      .each do |title|
      puts title
      session = title.split(/ /).first
      puts get_command_output_lines("tmux list-windows -t #{session}")
             .map { |window| window.sub(/\((\d+ panes)\).*$/, "(\\1 panes)") }

      puts
    end
  end

end


if __FILE__ == $0
  Application.new.run
end
