#!/usr/bin/env ruby
# tservices-start - hack to workaround my crippled tshare-start script

require_relative 'tmuxinatrix/tmux_settings'
require_relative 'tmuxinatrix/tmuxinatrix'

settingses = [
  TmuxSettings.new("ams", "application_management_system"),
  TmuxSettings.new("bas", "bank_account_service"),
  TmuxSettings.new("cra", "cra_products_emulator"),
  TmuxSettings.new("gc",  "global_customer"),
  TmuxSettings.new("cc",  "credit_card_service"),
  TmuxSettings.new("bms", "benefits_management_service"),
  TmuxSettings.new("cls", "cash_ledger_service"),
  TmuxSettings.new("lms", "lease_management_system"),
  TmuxSettings.new("cf",  "contract-funding"),
  TmuxSettings.new("kipper", "kipper"),
]
$logging = true

Tmuxinatrix.run('services', settingses)
