#!/usr/bin/env ruby
# tservices-start - hack to workaround my crippled tshare-start script

require_relative 'tmuxinatrix/tmux_settings'
require_relative 'tmuxinatrix/tmuxinatrix'

settingses = [
  TmuxSettings.new(name: "ams", folder: "application_management_system", commands: "bin/start"),
  TmuxSettings.new(name: "amq", folder: "application_management_system", commands: "bundle exec sidekiq"),
  TmuxSettings.new(name: "mpq", folder: "merchant_portal", commands: "bundle exec sidekiq"),
  TmuxSettings.new(name: "kipper", folder: "kipper", commands: "bin/start"),
]
$logging = true

Tmuxinatrix.run('services', settingses)
