#!/usr/bin/env ruby
# tservices-start - hack to workaround my crippled tshare-start script

require_relative 'tmuxinatrix/tmux_settings'
require_relative 'tmuxinatrix/tmuxinatrix'

settingses = [
  TmuxSettings.new(name: "ams", folder: "application_management_system", commands: "bin/start"),
  TmuxSettings.new(name: "ccs", folder: "credit_card_service", commands: ["frum local 3.2.1", "bin/rails server"]), # port 3015 is in .local.env
  TmuxSettings.new(name: "amq", folder: "application_management_system", commands: "bundle exec sidekiq"),
  TmuxSettings.new(name: "mpq", folder: "merchant_portal", commands: "bundle exec sidekiq"),
  TmuxSettings.new(name: "ccq", folder: "credit_card_service", commands: ["frum local 3.2.1", "bin/sidekiq"]),
  # TmuxSettings.new(name: "kipper", folder: "kipper", commands: "bin/start"),
  TmuxSettings.new(name: "anycable", folder: "merchant_portal", commands: "bundle exec anycable --log-grpc"),
  TmuxSettings.new(name: "anycable-go", folder: "kipper", commands: "anycable-go --host=0.0.0.0 --port=3334 --debug --rpc_host=localhost:50051"),
  # TmuxSettings.new(name: "cf", folder: "contract-funding", commands: "bin/start"),
  # TmuxSettings.new(name: "ci-deadman", folder: "../../../bin", commands: "ci-deadman"),
  # TmuxSettings.new(name: "git-watch", folder: "merchant_portal", commands: "watch -n 60 'git log-branch -p'"),
  # TmuxSettings.new(name: "elasticsearch", folder: "elasticsearch-8.11.3", commands: "bin/elasticsearch"),
]
$logging = true

Tmuxinatrix.run('services', settingses)
