#!/bin/bash

# TODO - I keep changing the list of windows and such. Maybe find a way to
# separate these? E.g. read in a list of window names & initial commands from an
# .rc file? Then the "for name in..." thing would be like "cat .twindowrc |
# while read name; do $TCMD -S /tmp/work new-window -n $name -t work; done"
#
# Or, more likely, change this to a ruby file and have a yaml file listing
# windows and the commands to be sent to them

$TCMD -S /tmp/work new-session -s work -n emacs -d

if [ `uname -s` == "Darwin" ]; then
    # window    2    3    4       5
    for name in spec bash logging scratch docker; do
        $TCMD -S /tmp/work new-window -n $name -t work
    done

    # get this party started
    # Clear the crap out of window 1, I mean, what even?
    $TCMD -S /tmp/work send-keys -t work:1 C-w

    $TCMD -S /tmp/work send-keys -t work:1 'emacs' C-m

    # leave window 2 (bash) alone

    # $TCMD -S /tmp/work send-keys -t work:3 'cd ~/cmm/vagrant/code' C-m
    # $TCMD -S /tmp/work send-keys -t work:3 'vagrant ssh' C-m

    # Start vagrant. Because I'm doing this in two windows at once, I often get
    # errors saying that the VM is locked. Which window barfs is nondeterministic,
    # so tack on this messy check/retry/giveup bit to all windows with the temerity
    # to start vagrant.
    # $TCMD -S /tmp/work send-keys -t work:4 'cd ~/cmm/vagrant/code' C-m
    # $TCMD -S /tmp/work send-keys -t work:4 'vagrant ssh || (echo VAGRANT SSH FAILED, RETRYING IN 5s...; sleep 5; vagrant ssh || echo VAGRANT SSH FAILED AGAIN, GIVING UP)' C-m

    # Start vagrant. Because I'm doing this in two windows at once, I often get
    # errors saying that the VM is locked. Which window barfs is nondeterministic,
    # so tack on this messy check/retry/giveup bit to all windows with the temerity
    # to start vagrant.
    # $TCMD -S /tmp/work send-keys -t work:5 'cd ~/cmm/vagrant/code' C-m
    # $TCMD -S /tmp/work send-keys -t work:5 'vagrant ssh || (echo VAGRANT SSH FAILED, RETRYING IN 5s...; sleep 5; vagrant ssh || echo VAGRANT SSH FAILED AGAIN, GIVING UP)' C-m

    # $TCMD -S /tmp/work send-keys -t work:5 '' C-m

else
    # Linux, most likely
    # window    2    3    4       5
    for name in spec bash console; do
        $TCMD -S /tmp/work new-window -n $name -t work
    done

    # get this party started

    # Clear the crap out of window 1, I mean, what even?
    $TCMD -S /tmp/work send-keys -t work:1 C-w

    $TCMD -S /tmp/work send-keys -t work:1 'emacs' C-m
fi

# Select window 1 and attach to it
$TCMD -S /tmp/work select-window -t work:1
$TCMD -S /tmp/work -2 attach -t work


# NOTES

# How to rename a window after you've created it
# $TCMD -S /tmp/work rename-window -t work:1 newname
