#!/usr/bin/env ruby
# twork-start - hack to workaround my crippled tshare-start script

require_relative 'tmuxinatrix/tmux_settings'
require_relative 'tmuxinatrix/tmuxinatrix'

settingses = [
  TmuxSettings.new("emacs", "merchant_portal", "emacs"),
  TmuxSettings.new("bash", "merchant_portal", ""),
  TmuxSettings.new("spec", "merchant_portal", ""),
  TmuxSettings.new("console", "merchant_portal", ""),

  TmuxSettings.new("mp", "merchant_portal"),
  TmuxSettings.new("mpq", "merchant_portal", "besq"),
  TmuxSettings.new("np", "notary_public"),
  TmuxSettings.new("uw", "underwriting"),
]
$logging = true

Tmuxinatrix.run('work', settingses)
