#!/usr/bin/env ruby
require 'fileutils'

# vpnwatch: Know when the vpn is down
# Can do this in a one-off bash command as:
# ping -c 1 -t 10 google.com && echo "Network is up" || echo "Network is DOWN"
#
# -c 1 exits after sending 1 packet
# -t 10 exits with failure code if no response received in 10 seconds

# TODO:

# - [ ] Add a happy alert when network is up / comes back up

# - [ ] Cmd-line options:
#   - do/don't truncate log at startup
#   - Play/don't play sad alert when network is down: never, once, always
#   - Play/don't play happy alert when network is up: never, once, always
#
#   - "once" means "this is different than the previous event", i.e. an edge
#     trigger. Plays the sound unless the previous event was the same.

# - [ ] Change logfile to database maybe, and instead of truncating, have a
#   session list. Be interesting to chart uptime/downtime vs. time of day, since
#   the perception is that the vpn goes down a lot in the afternoons and almost
#   never in the mornings.

def logfile
  File.expand_path(File.join(File.dirname(__FILE__), "vpnwatch_logs/vpnwatch.#{Time.now.strftime('%F.%H%M')}.log"))
end

def truncate_log
  File.open(logfile, "w") do |fp|
  end
end

def log_to_file(msg)
  File.open(logfile, "a") do |fp|
    fp.print msg
  end
end

def log_start
  time = Time.now
  msg = time.strftime("%F %T ")
  print msg
  $stdout.flush
  log_to_file msg
end

STATUS_FILE = File.expand_path("~/.vpnwatch_is_currently_down")

def was_down?
  File.exist?(STATUS_FILE)
end

def log_down_status
  File.open(STATUS_FILE,"w") { |fp| fp.puts Time.now.strftime("%F %T") }
end

def clear_down_status
  FileUtils.rm(STATUS_FILE)
end

def log_finish(success)
  time = Time.now
  msg = time.strftime("(%F %T): ")
  msg += if success
           "\033[1;37;42mNetwork is UP\033[0m"
         else
           "\033[1;37;41mNetwork is DOWN\033[0m"
         end
  puts msg
  log_to_file "#{msg}\n"
  if success && was_down?
    clear_down_status
    play_happy_sound
  elsif !success
    log_down_status
    play_alert_sound
  end
end

def log_no_vpn
  time = Time.now
  msg = time.strftime("(%F %T): ")
  msg += "\033[2;37mNO VPN RUNNING\033[0m"
  puts msg
  log_to_file "#{msg}\n"
end

def play_alert_sound
  sound_file = '/System/Library/Sounds/Basso.aiff'
  # File.expand_path(File.join(File.dirname(__FILE__), "thunderclap.mp3"))
  system "afplay #{sound_file}"
end

def play_happy_sound
  sound_file = '/System/Library/Sounds/Purr.aiff'
  # File.expand_path(File.join(File.dirname(__FILE__), "thunderclap.mp3"))
  system "afplay #{sound_file}"
end

truncate_log
puts "SOUND CHECK!"
print "When network is down: "
play_alert_sound
puts "Done."
print "When network comes back up: "
play_happy_sound
puts "Done."

while true do
  log_start
  # if [[ $(ifconfig | grep "mtu 1406" ) ]] <-- check to see if vpn THINKS it is running
  # ^^^ mtu 1406 is the old AnyConnect. Need to diff the new vpn, it's not 1406.
  #
  # Perhaps this might be better: on the new vpn, an entirely new network
  # connection appears, "utun2". It may also be telling that this is the only
  # 10.x.x.x connection in my network.
  #
  # utun2: flags=80d1<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST> mtu 1390
  #        inet 10.1.40.204 --> 10.1.40.204 netmask 0xffffffff
  #        inet6 fe80::8a66:5aff:fe03:c480%utun2 prefixlen 64 scopeid 0x12
  #        inet6 fe80::33e6:36c4:883a:37b1%utun2 prefixlen 128 scopeid 0x12
  #        nd6 options=201<PERFORMNUD,DAD>
  #
  # Okay, checking for utun doesn't work either. mtu is the "Maximum
  # Transmission Unit" and UTUN is how Catalina (and later) describes any
  # virtual network, including Docker talking to itself.
  #
  # The best way to catch this is to look for an utun that runs on a 10.x.x.x
  # ip4 network.

  vpn_running = system('ifconfig | grep -A 1 -E "^utun:" | grep "inet 10.1.40" 2>&1 >/dev/null')
  if vpn_running
    network_ok = system("ping -c 1 -t 1 google.com 2>&1 >/dev/null")

    log_finish(network_ok)
  else
    log_no_vpn
  end

  # Try to fire off every minute at the top of the minute
  sec_until_next_minute = 60 - Time.now.sec

  # In theory, Time.now.sec can be 60 or even 61 if we're in a leap second.
  # If that happens, I'd love to see this program crash!
  sleep sec_until_next_minute
end
