#!/usr/bin/env ruby
# watch-and-say - because multiple tmates break the say command, grr
# watch-and-say [queue_filename]
#
# If omitted, queue_filename will be ~/.watch_and_say
require 'fileutils'

watch_file = if ARGV.size.zero?
               "~/.watch-and-say"
             elsif File.directory?(File.dirname(ARGV[0]))
               ARGV[0]
             else
               File.join(Dir.getwd, ARGV[0])
             end

watch_file = File.expand_path watch_file

# Clean out anything already in there
if File.exists? watch_file
    puts "Clearing out existing watch file at #{watch_file}..."
    FileUtils.rm_f watch_file
end

puts "Watching #{watch_file}..."
while true
  if File.exist? watch_file
    text = File.readlines watch_file
    FileUtils.rm_f watch_file
    text.each do |line|
      line = line.strip
      puts "Saying #{line}..."
      system "say", line
    end
  end
  sleep 1
end
