#!/bin/bash
echo "Watching specs run..."
say Watching specs run

while [[ /bin/true ]]; do
    echo "Checking to see if specs have started running..."
    echo -n $(date +'%F %T:')
    if [[ ! -e "specs_are_running.txt" ]] ; then
        # say "specs are not running."
        # Use a random voice instead
        voice=$(say -v ? | ruby -ne 'puts $_.sub(/   .*/, "")' | randline)
        echo "  specs are not running. ($voice)"
        say -v "$voice" specs are not running
    else
        echo " specs are running."
    fi
    sleep 10
done
