#!/usr/bin/env ruby
# which-tables-are-mentioned-in-this-job [-q|--quiet] - try to find tables (by prefix) mentioned in this job
require 'optimist'
require 'colorize'

if `uname -s`.strip == 'Darwin'
  puts "You are in OSX. DS script only makes sense from inside Docker. Aborting.".light_yellow
  exit -1
end

opts = Optimist.options do
  opt :quiet, "Don't show search commands", default: false
end

# TODO: Search for and prioritize create table <table> statements
# TODO: Get the dst_table, if any, from the config
# TODO: A couple jobs use src_table and routing_table in the config

argv=ARGV.dup
script = argv.first || `get-ds-script`.rstrip

if script.empty?
  puts "You must set the SCRIPT variable or pass in an argument first."
  exit -1
end

command = "cat #{script} | ruby -ne 'puts $1 if $_=~/\\b((lms|mp|uw|ecom|d|f|s)_.*?)\\b/' | sort | uniq"
puts command.cyan unless opts[:quiet]
system command
