#!/usr/bin/env ruby
# which-tables-are-mentioned-in-this-job [-q|--quiet] - try to find tables (by prefix) mentioned in this job
# TODO: require 'optimist'
require 'colorize'

if `uname -s`.strip == 'Darwin'
  puts "You are in OSX. DS script only makes sense from inside Docker. Aborting.".light_yellow
  exit -1
end

argv=ARGV.dup
quiet = argv.delete('-q') || argv.delete('--quiet')
script = argv.first || `get-ds-script`.rstrip

if script.empty?
  puts "You must set the SCRIPT variable or pass in an argument first."
  exit -1
end

command = "cat #{script} | ruby -ne 'puts $1 if $_=~/\\b((lms|mp|uw|ecom|d|f|s)_.*?)\\b/' | sort | uniq"
puts command.cyan unless quiet
system command
